### ISSUE TITLE
Object Property candidates for consolidation

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1009]
Pertains to 2020/Q1 Production (not urgent).
The latest release unified object properties of the same (local) name and sematic that occur in more than one ontology (FIBO and LCC). 
Here are still four object properties that are in different FIBO ontologies. For example, do we need a special hasPaymentSchedule for Derivatives, or can we extend the Foundation object property?

object_property | skos_definition | Localname
-- | -- | --
fibo-fnd-rel-rel:evaluates | assesses the nature, quality, or   ability of someone or something | evaluates
fibo-fnd-utl-alx:evaluates | calculates a quantity value based on   some mathematical formula | evaluates
fibo-der-drc-swp:hasPaymentSchedule | defines a schedule of payments for a   funding leg of a swap | hasPaymentSchedule
fibo-fnd-pas-psch:hasPaymentSchedule | specifies the schedule for payment of   an obligation | hasPaymentSchedule
fibo-fbc-dae-dbt:isBasedOn | relates something to something else on   which it rests, or that supports it in some way | isBasedOn
fibo-sec-dbt-bnd:isBasedOn | indicates the economic indicator or   market rate on which an index-based security depends | isBasedOn
fibo-fnd-rel-rel:isEvaluatedBy | is ascertained or determined by | isEvaluatedBy
fibo-fnd-utl-alx:isEvaluatedBy | links a quantity value to the   expression that generated it | isEvaluatedBy

**Comment by trypuz** [comment]
Related issue: #875

**Comment by ElisaKendall** [comment]
Thanks Jurgen - I'm surprised that there are not more of these.  They probably each need some analysis to determine whether or not they are really the same, whether we need to rename but retain some of them, or consolidate them as you suggest.  There are far more duplicates in the provisional ontologies that really need to be addressed before they can be integrated into our released set, but this is a good catch.

**Comment by rivettp** [comment]
This is not only "relatedTo" #875 it's a complete subset. Do we need to keep this duplicate open?
FWIW apart from hasPaymentSchedule these property pairs seem to have quite distinct meanings so should *not* be merged: we should rename one of them if we think the unique labels policy justifies the effort (including deprecating the original and updating of references to the renamed one).

**Comment by jziemer2** [comment]
No more of these in Prod, @ElisaKendall 
The only four reused Class Localnames below are external. 
class | skos_definition | localname
-- | -- | --
lcc-cr:Alpha2Code | a digraph representing a country or   geographic region | Alpha2Code
lcc-lr:Alpha2Code | a language identifier for a human   language as defined by ISO 639-1, that is, a two-letter combination of   characters used to represent a language or languages | Alpha2Code
lcc-cr:Alpha3Code | a trigraph representing a country or   geographic region | Alpha3Code
lcc-lr:Alpha3Code | a language identifier for a human   language as defined by ISO 639, that is, a three-letter combination of   characters used to represent a language or languages | Alpha3Code
lcc-lr:Collection | a grouping of some variable number of   things (may be zero) that have some shared significance | Collection
skos:Collection | A meaningful collection of concepts. | Collection
fibo-fnd-org-org:Organization | collection of one or more people, or   groups of people formed together into a community or other social, commercial   or political structure to act, or that is designated to act, towards some   purpose, such as to meet a need or pursue collective goals on a continuing   basis | Organization
sm:Organization | an entity, such as an institution or   an association, that has a collective goal and is linked to an external   environment | Organization

**Comment by trypuz** [comment]
Closed due to implementing a new hygiene test #1069
