### ISSUE TITLE
Duplicate Object Properties

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1019]
Pertains to https://spec.edmcouncil.org/fibo/ontology/master/latest/dev.ttl.zip
Same as #1018, the dot in ".1" looks tool generated rather than ontologist intention.

The list shows duplicate Object Properties with an incrementing number at the end.
fibo-bp-iss-muni:subscriber.1
fibo-bp-iss-muni:subscribesTo.1
fibo-bp-iss-pmbs:finalizes.1
fibo-bp-iss-pmbs:hasContent.1
fibo-bp-iss-pmbs:hasResource.1
fibo-bp-iss-pmbs:hasResource.2
fibo-bp-iss-pmbs:includesDetailsAbout.1
fibo-bp-iss-pmbs:requires.1
fibo-bp-iss-pmbs:resultsIn.1
fibo-bp-iss-pmbs:resultsIn.2
fibo-cae-ce-cae:announcedBy.1
fibo-cae-ce-cae:conveys.1
fibo-cae-ce-cae:conveys.2
fibo-cae-ce-cae:relatesTo.10
fibo-cae-ce-cae:relatesTo.11
fibo-cae-ce-cae:relatesTo.12
fibo-cae-ce-cae:relatesTo.13
fibo-cae-ce-cae:relatesTo.15
fibo-cae-ce-cae:relatesTo.16
fibo-cae-ce-cae:relatesTo.17
fibo-cae-ce-cae:relatesTo.18
fibo-cae-ce-cae:relatesTo.2
fibo-cae-ce-cae:relatesTo.3
fibo-cae-ce-cae:relatesTo.4
fibo-cae-ce-cae:relatesTo.5
fibo-cae-ce-cae:relatesTo.6
fibo-cae-ce-cae:relatesTo.7
fibo-cae-ce-cae:relatesTo.8
fibo-cae-ce-cae:relatesTo.9
fibo-civ-fnd-civ:hasDistributionPolicy.1
fibo-civ-fnd-civ:hasDistributionPolicy.2
fibo-civ-fnd-civ:hasPolicyTerms.1
fibo-civ-fnd-civ:identifiedAs.3
fibo-civ-fnd-civ:identifiedAs.5
fibo-civ-fnd-civ:identifies.1
fibo-civ-fnd-civ:inceptionDate.1
fibo-civ-fnd-civ:mayBe.1
fibo-der-ass-eqo:includesSpecification.1
fibo-der-ass-eqs:hasComponent.1
fibo-der-cr-cds:defaultRequirement.1
fibo-der-cr-cds:definedAs.1
fibo-der-cr-cds:definedAs.2
fibo-der-cr-cds:specifies.1
fibo-der-cr-cds:specifies.2
fibo-der-der-fwd:establishes.1
fibo-der-der-fwd:side.1
fibo-der-der-opt:hasExpression.1
fibo-der-der-opt:hasFormula.1
fibo-der-der-opt:makes.1
fibo-der-der-opt:receives.1
fibo-der-der-opt:setsOut.1
fibo-der-der-opt:subtracts.1
fibo-der-der-opt:subtractsFrom.1
fibo-der-drc-ma:invokedInEventOf.1
fibo-der-drc-ma:specifies.1
fibo-der-etd-eto:strikePrice.1
fibo-der-etd-eto:strikePrice.3
fibo-der-fx-fwd:hasPart.1
fibo-der-fx-fwd:side.1
fibo-der-fx-opt:establishes.1
fibo-loan-tem-ev:resultsIn.1
fibo-loan-tem-sta:informationDate.1
fibo-loan-typ-sec:howSecured.2
fibo-md-civx-fun:determinationDate.1
fibo-md-civx-fun:incursFees.1
fibo-md-civx-fun:incursTax.1
fibo-md-dbtx-aly:aggregateOf.1
fibo-md-dbtx-aly:averageLifeValue.1
fibo-sec-dbt-ab-cdo:hasTranche.1
fibo-sec-dbt-ab-cdo:hasTranche.2
fibo-sec-dbt-ab-cdo:hasTranche.3
fibo-sec-dbt-ab-cdo:managementStyle.1
fibo-sec-dbt-ab-cdo:origination.2
fibo-sec-dbt-ab-cdo:ratedAtIssue.1
fibo-sec-dbt-ab-cdo:structure.2
fibo-sec-dbt-ab-cmo:specifies.1
fibo-sec-dbt-ab-cmo:takesPrepaymentAfter.1
fibo-sec-dbt-ab-mbs:denomination.1
fibo-sec-dbt-ab-mbs:isAlso.1
fibo-sec-dbt-ab-pbs:hasUnderlying.1
fibo-sec-dbt-ab-syn:simulates.1

**Comment by ElisaKendall** [comment]
Like the data properties, these were created when the OWL was generated from Excel and Enterprise Architect in 2013-2014, and are in provisional ontologies only.  They and other duplicates need to be eliminated over time as those ontologies are brought into release.  Hundreds of others like these have been eliminated over the last several years.

**Comment by ElisaKendall** [comment]
This issue corresponds to FND-198 in JIRA, raised 2018-05-29, at which time there were 124 of these remaining.

**Comment by jziemer2** [comment]
Thanks Elisa.

@trypuz Robert, the issue is about duplicate URIs.
I believe the labels are unique.

**Comment by trypuz** [comment]
Closed due to implementing a new hygiene test #1069
