### ISSUE TITLE
Namespace misnamed in DerivativesMasterAgreements.rdf

### ISSUE THREAD

**Issue by bblfish** [edmcouncil/fibo#1064]
I was trying to build a unified namespace for FIBO, which led me to notice the following errors.
In [DerivativesMasterAgreements.rdf](https://github.com/edmcouncil/fibo/blob/master/DER/DerivativesContracts/DerivativesMasterAgreements.rdf) you are using the `fibo-fnd-arr-arr`
namespace where I think it should be `fibo-fnd-arr-doc`

```xml
  <!ENTITY fibo-fnd-arr-arr "https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/">
```

**Comment by rivettp** [comment]
Correct, I was a bit concerned but checked the entity use is localized to just 2 properties which are in Documents - so though it should be fixed it does not have any impact.

**Comment by trypuz** [comment]
Fixed.
