### ISSUE TITLE
Role of hygiene test in ontology testing

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1066]
It seems to me that it is possible that a prod-level version of FIBO has unresolved hygiene issues.

I run https://github.com/edmcouncil/fibo/blob/master/etc/testing/hygiene/testHygiene0001.sparql on prod.fibo-quickstart.ttl from Q2 2020 and got 100+ failures, i.e. RDF nodes without rdf:type - as far as I can tell they are all ontologies that are not declared as of type owl:Ontology. [testhygiene001_fails_2020_q2.txt](https://github.com/edmcouncil/fibo/files/4846395/testhygiene001_fails_2020_q2.txt)

Apparently, hygiene failures are somehow by-passed in the automation.
This is not a definitive remark since we know that there are differences between different FIBO products as reported in https://github.com/edmcouncil/fibo/issues/1065.

**Comment by ElisaKendall** [comment]
These are all declared in the RDF/XML version, so something is going wrong in the translation to Turtle or in how we produce the quickstart.

**Comment by mereolog** [comment]
I run this test on LoadFIBOProd and indeed all missing types were found.
Thus this issue is an offshot of https://github.com/edmcouncil/fibo/issues/1065 and can be closed for now.
However we still need to check that the hygiene tests, if fail, make the Jenkins process terminate with an appropriate error.
