### ISSUE TITLE
FIBO 2020/Q2 Prod - No Isssues!

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1076]
Kudos, FIBO Team,
The latest Prod opens without issues. Configuration Management and QC are no small feats with hundreds of files and thousands of classes & properties.
https://spec.edmcouncil.org/fibo/ontology/master/2020Q2/prod.ttl.zip
![TCB FIBO Classes query](https://user-images.githubusercontent.com/11173121/86472634-75fd9900-bd0d-11ea-954d-03e89770d60f.png)

**Comment by trypuz** [comment]
@jziemer2 thank you for your support! Best
