### ISSUE TITLE
Q2 PROD - Primary Party inverseOf  playsActiveRoleIn

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1077]
The owl:inverseOf looks like a bug:
https://spec.edmcouncil.org/fibo/ontology/master/2020Q2/prod.ttl.zip
```
fibo-fnd-pty-pty:hasPrimaryParty
  rdf:type owl:ObjectProperty ;
  rdfs:comment "QName: fibo-fnd-pty-pty:hasPrimaryParty" ;
  rdfs:isDefinedBy fibo-fnd-pty-pty: ;
  rdfs:label "has primary party" ;
 owl:inverseOf fibo-fnd-pty-pty:playsActiveRoleIn ;
  owl:propertyChainAxiom (
      fibo-fnd-pty-pty:hasActor
      fibo-fnd-pty-rl:isPlayedBy
    ) ;
  <http://www.w3.org/2004/02/skos/core#definition> "relates a situation to the person or organization acting in a primary (agentive) role" ;
.
```

**Comment by ElisaKendall** [comment]
Hi Jurgen, 

This is part of a set of patterns added to cover lattice relations, especially for ownership and control relationships between roles - what about this looks incorrect to you?  We are attempting to create better patterns and normalize the properties for some of these reified relations, which will include control, beneficial ownership, etc., fyi.  There will be more revisions that use these over the next month or so, but what's there has been tested with our example data for subsidiaries, holding companies, etc.  People often choose the wrong ones, resulting in reasoning errors.  

Best,

Elisa
