### ISSUE TITLE
Extending hygiene tests set - never use rdfs:comment

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1079]
https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#minimal-compliance-hygiene-tests suggests a test to the effect that rdfs:comment be not used.

If this check is still endorsed by the FIBO community, I think the SPARQL query posted there may be simplified as follows.
AS IS:
```
SELECT ?Resource ?Type ?Comment 
	WHERE { ?Resource rdf:type ?Type .
	?Resource rdfs:comment ?Comment. 
	FILTER(?Type in (owl:Class, owl:DatatypeProperty, owl:ObjectProperty ))
	FILTER(!(STRSTARTS(STR(?Resource), # ignore things in owl namespace
	"http://www.w3.org/2002/07/owl#") ))
	FILTER(!(STRSTARTS(STR(?Resource), # ignore things in skos namespace
	"http://www.w3.org/2004/02/skos/core#") ))
	}
	ORDER BY ?Type ?Resource
```
MAY BE
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?error ?o
WHERE 
{
  ?s rdfs:comment ?o 
  FILTER (CONTAINS(str(?s), "edmcouncil"))
  BIND (concat ("WARN: ", str(?s), " has rdfs:comment annotation.") AS ?error)
}
```
Note however that rdfs:comment is being used in quick versions of FIBO to store qualified names, so may be this text is obsolete now?

**Comment by ElisaKendall** [comment]
I think we want to use this on the git versions of the ontologies, but perhaps skip individuals, especially those that are generated for the time being.  It could be a warning for individuals and error for classes and properties.  For anything produced by the publisher you could have other rules, such as for the quick versions.

**Comment by dallemang** [comment]
Speaking of this, there is a process in the publisher that puts the QName into a rdfs:comment.  This was to get around a failing in Widoco, that was long since remediated by the viewer.   We should remove that from the ontology-publisher.
