### ISSUE TITLE
Eliminate reasoning complexity due to the union in hasTag in the relations ontology

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1082]
The hasTag property in relations is defined as multivalued, and unnecessarily increases inefficiencies in reasoning as well as confusion with the hasTag property in LCC, which is sufficient for the use cases we have identified for FIBO. It should be replaced in all remaining uses with the FIBO hasTag property and eliminated.

This issue is related to #1043.

**Comment by rivettp** [comment]
I think in the last sentence "It should be replaced in all remaining uses with the FIBO hasTag property and eliminated." it should say "It should be replaced in all remaining uses with the **LCC** hasTag property and eliminated."
