### ISSUE TITLE
Duplication in release note detail due to including both PRs and Issues

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#1086]
For example the following is the link for FBC: https://github.com/edmcouncil/fibo/issues?q=milestone%3A%222020+Q2+FIBO+Release%22+label%3AFBC+ 

The query shows both PRs and the original Issue - so each change generally appears twice with subtly different wording, which clogs things up. Except a closed issue will also appear even if no change was made or needed.
Best I think to only list the merged PRs - people can always drill through to the issue.

**Comment by trypuz** [comment]
It was my intention to have both PRs and issues grouped together. Though we shouldn't have issues here that have not been resolved.

**Comment by rivettp** [comment]
Still don't see why it makes sense to have both in the same list: even if they are next to each other it's just clutter for minimal value, given you can drill down from the PR to the issue.

**Comment by trypuz** [comment]
Hi Pete, the current setting simplifies access to information; what has changed, and what is currently under development (in the issues list, the milestone label helps distinguish between issues that are linked with PRs and those that are waiting for being tackled). I see value in it, even if you call it "minimal". I'm closing this issue. Thank you for your comment.
