### ISSUE TITLE
The domain of of several properties should not be 'Reference', which is too narrow

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1095]
Other things can be defining concepts, so the domain declaration for 'defines' is too restrictive. The same issue is true of appliesTo, characterizes, and hasArgument.  Some of their definitions need to be made ISO 704 compliant as well.

**Comment by CoryCasanave** [comment]
I hope you replace the domain with something, every property is about something more specific than “thing”

**Comment by ElisaKendall** [comment]
@CoryCasanave I think in these cases that would be tough - they are really general properties, although there may be a class that would work for characterizes, but I'd need to do quite a bit of testing to ensure that doesn't have unintended consequences, which the original domain(s) did for these.

**Comment by rivettp** [comment]
It makes me question what is the value of such general properties? When would you ever query ?s :characterizes x? You'd always use a more specific property. Or filter on the class of ?s. The only argument I've ever heard is that it makes it easier to navigate in limited tools like Protege. Even then I'd disagree - how is someone to know whether to look under classifies or characterizes?

**Comment by ElisaKendall** [comment]
For characterizes, I think the domain could be Aspect - doing some research to see if that will work, but that change has to be made in Analytics, not in Relations, to avoid circular dependencies.
