### ISSUE TITLE
FIBO Domain for General Ledger, Profit & Loss as well as Capital Market Ratio available?

### ISSUE THREAD

**Issue by ebnerj** [edmcouncil/fibo#1104]
Dear FIBO Team,
I understand that the FIBO Content Teams (FCTs) are working groups that are formed when the FIBO Community Group decides what existing or new FIBO Domain should be further developed. 

Maybe I overlooked this, but I could not see what is all in the Pipeline. I understood that the complete overview of all avalable FIBO ontologies are available here: https://spec.edmcouncil.org/fibo/ontology/

I am basically trying to find out more if within FIBO an ontology for General Ledger, Profit & Loss and / or more general available Capital Market Ratios exist. Is someone able to help me?

I understand that multiple regulator and companies have published different standards for reporting purposes based on available GAAP but what I was looking a general global standard around this which is not linked to any of the XBRL standards or similarly.

Thanks a lot for your help

Best regards
Johannes

**Comment by rivettp** [comment]
Speaking personally, I would see Capital Market Ratios being in the scope of FIBO - we've started exploring areas such as market cap. 
However I would argue that generic accountancy concepts such as General Ledger would not be in scope (FIBO is already arguably too large, and as I'm sure you're aware there are both US GAAP and IFRS perspectives to consider). I'm involved in work happening in OMG around the Standard Business Report Model https://www.omgwiki.org/SBRM/doku.php that is intended to bring an ontology treatment to XBRL; that provides the structure and the aggregation and allows Accountancy subject matter experts to contribute the ontology for the core accounting concepts: we do have some of those onboard.

**Comment by ebnerj** [comment]
> Speaking personally, I would see Capital Market Ratios being in the scope of FIBO - we've started exploring areas such as market cap.
> However I would argue that generic accountancy concepts such as General Ledger would not be in scope (FIBO is already arguably too large, and as I'm sure you're aware there are both US GAAP and IFRS perspectives to consider). I'm involved in work happening in OMG around the Standard Business Report Model https://www.omgwiki.org/SBRM/doku.php that is intended to bring an ontology treatment to XBRL; that provides the structure and the aggregation and allows Accountancy subject matter experts to contribute the ontology for the core accounting concepts: we do have some of those onboard.

Thanks a lot rivettp for your feedback. Very much appreciated

**Comment by ElisaKendall** [comment]
@ebnerj  Hi Johannes,

Pete is right for the most part - we have a few very high level accounting concepts.  FIBO includes individuals for IFRS and US GAAP, and classes for 'ledger account' and for GL, but we haven't integrated details at a transaction / record level, or for the many other accounting concepts that would allow for representation and roll-up of a P/L statement or balance sheet, and that's really not in scope for FIBO.  I'm working with a client for which we've represented a general transaction record, and hope to integrate that soon, which might get you partway there.  We also have a number of concepts describing statistical measures that might be useful, which we developed with the assistance of Statistics Canada and the Bureau of Labor Statistics. 

If you would like a cook's tour of those aspects of the model that you might be able to reuse, please don't hesitate to ask - we can set up a webex for that over the next couple of weeks.  My email address is ekendall@thematix.com, and Pete's is pete.rivett@adaptive.com - feel free to send us a note if that would be helpful and we can set up a time.

Best regards,

Elisa

**Comment by ebnerj** [comment]
> @ebnerj Hi Johannes,
> 
> Pete is right for the most part - we have a few very high level accounting concepts. FIBO includes individuals for IFRS and US GAAP, and classes for 'ledger account' and for GL, but we haven't integrated details at a transaction / record level, or for the many other accounting concepts that would allow for representation and roll-up of a P/L statement or balance sheet, and that's really not in scope for FIBO. I'm working with a client for which we've represented a general transaction record, and hope to integrate that soon, which might get you partway there. We also have a number of concepts describing statistical measures that might be useful, which we developed with the assistance of Statistics Canada and the Bureau of Labor Statistics.
> 
> If you would like a cook's tour of those aspects of the model that you might be able to reuse, please don't hesitate to ask - we can set up a webex for that over the next couple of weeks. My email address is [ekendall@thematix.com](mailto:ekendall@thematix.com), and Pete's is [pete.rivett@adaptive.com](mailto:pete.rivett@adaptive.com) - feel free to send us a note if that would be helpful and we can set up a time.
> 
> Best regards,
> 
> Elisa

Thanks Elisa - very much appreciated. I will look into the details and connect with you
