### ISSUE TITLE
Review of hygiene tests - bad characters check

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1119]
https://github.com/edmcouncil/fibo/blob/master/etc/testing/hygiene/testHygiene0114.sparql reports triples' objects that contain "special characters". The latter are currently defined by this regex: [ÁáÇçÉéÍíÕõÖöäÄèÈμΜσΣa-zA-Z\\\\;'?@$%#&:/\"<*>,._+÷=)(\\[\\]{}0-9\n\t -].

This check may return a number of false positives, i.e., it may report cases where all chars are FIBO compliant, e.g., it will report "ó" in "jurisdiction of the Suprema Corte de Justicia de la Nación".

We may extend the current regex to include the valid chars - the problem here is how to avoid an ad hoc update. To do this we should probably first determine the list of languages in FIBO scope and then include all diacritic chars for these languages in the regex.

Alternatively we may remove the check altogether or downgrade it to a "warning" check.

**Comment by ElisaKendall** [comment]
@mereolog - ultimately we will be including jurisdictions for every country in the world.  I can go back and review those that include diacritics, and see if they should be in language tagged strings, but I'm not sure that makes sense.  When you talk about a place or jurisdiction, it should be possible to include the local name for that place in a string that includes English definitions, as long as the character is proper unicode.  But we should disallow it in class/property/individual names (fine in labels and other annotations as long as tools can process it)
