### ISSUE TITLE
Collection is no longer an Arrangement?

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1144]
FIBO Production:
I understand that 2020-Q1 merged the equivalent class fibo-fnd-arr-arr:Collection into lcc-lr:Collection. 
The FIBO Foundation class, fibo-fnd-arr-arr:Collection was rdfs:subClassOf fibo-fnd-arr-arr:Arrangement. The 2020-Q2 LCC class, is only rdfs:subClassOf the Thing. 

I think the original conceptualization made sense and suggest:
`lcc-lr:Collection rdfs:subClassOf fibo-fnd-arr-arr:Arrangement`

**Comment by rivettp** [comment]
FIBO's previous definition for Arrangement was equivalentTo the Arrangement class in LCC. The definition of Arrangement is "a structure or means of organizing information such as a schema, numbering system, organization scheme, measurement system, taxonomy, or language for organizing information".
That is a lot more specific than the general notion of Collection "a grouping of some variable number of things (may be zero) that have some shared significance" and so I think it was correct to remove that subclassing. LCC does have both classes, and they are unrelated.

BTW your specific suggestion (to make LCC Collection a subclass of FND Arrangement) would make LCC dependent on FND which would make for circular dependency (as FND is dependent on LCC already) which is against our rules.

**Comment by jziemer2** [comment]
Got it. Thanks for your prompt response, Pete.
