### ISSUE TITLE
Circular owl:imports

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1152]
If you run the following query over a recent FIBO Development, you will get 39 ontologies that either directly or indirectly import themselves.
```
prefix owl:<http://www.w3.org/2002/07/owl#>


SELECT DISTINCT ?ontology
WHERE
{
    ?ontology owl:imports+ ?ontology.
}
```
Among them there are two that have direct circular imports:
1. BusinessCenters
```
<owl:Ontology rdf:about="https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/BusinessCenters/">
[...]
<owl:imports rdf:resource="https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/BusinessCenters/"/>
```
2. LoanHMDA
```
<owl:Ontology rdf:about="https://spec.edmcouncil.org/fibo/ontology/LOAN/LoanContracts/LoanHMDA/">
[...]
<owl:imports rdf:resource="https://spec.edmcouncil.org/fibo/ontology/LOAN/LoanContracts/LoanHMDA/"/>
```

IMO direct circular imports should raise at least PRODERRORs if not ERRORs.
(They are easy to fix, so perhaps the latter.)
Also indirect imports are wrong - I am not sure whether they should be raised as WARNs or PRODERRORs.

In any case we need to have one or two hygiene tests.

**Comment by ElisaKendall** [comment]
Wow - these have been in there for quite a while.  Please do create a test for this, but I'll address them this week for the Q3 release
