### ISSUE TITLE
The new hygiene test for ambiguous definitions is far to simplistic and overreaching

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1160]
The number of warnings this produces is huge, and although some definitions are likely ambiguous, most of the ones identified through this test are false positives.

I'll add a list of some of the results to demonstrate the issue, but it will only be a subset of the total since there are so many of them.

**Comment by ElisaKendall** [comment]
Out of the first 20 of these 'warnings' I grabbed at most 2 of them are actually ambiguous... that's a 90% failure / false positive rate.  

[FalsePositiveRateForOr-20200919.xlsx](https://github.com/edmcouncil/fibo/files/5252476/FalsePositiveRateForOr-20200919.xlsx)

The way to do this properly could involve the use of NLP to find 'or' in the "head" phrase of the definition - not all of those would be ambiguous either, but that would reduce the number of false positives by an order of magnitude.  As it stands, this makes finding real issues and correcting them impossible.  Until this is removed, I'm ignoring hygiene testing altogether unless something is kicked out as an error.

**Comment by rivettp** [comment]
I strongly disagree with your analysis, @ElisaKendall. Attached is your spreadsheet with an additional column rebutting all your "false positive" claims. Yes it will take some effort to clean this up, and no it's not urgent, but IMO this precision and tightening up of definitions is a lot more important than the ISO 704 tweaks you make as you edit ontologies.
[FalsePositiveRateForOr-20200921.xlsx](https://github.com/edmcouncil/fibo/files/5257543/FalsePositiveRateForOr-20200921.xlsx)

**Comment by VladimirAlexiev** [comment]
A very interesting discussion. 

Let's look at this example:
- hasTransliteratedAddress: identifies a transliterated (i.e., in Latin or Romanized ASCII) address for the registered entity
  - Pete: just need to say “ASCII”
I agree the definition is ambiguous, but transliteration/romanization does not mean ASCII. In fact many transliterations use lots of accents, eg pinyun, wade-giles (for Chinese), LOC transliteration (uses ligatures for Russian letters like Я)... I'm no linguist, but accents may be required for many transliterations, i.e. reducing to ASCII will produce bad results.
So if you restrict hasTransliteratedAddress to ASCII, that may fail to accommodate actual instance data. If that came from GLEI, we need to look at actual GLEI data to see whether accents are used.

My point is, removing ambiguity will sometimes come to important design decisions or restrictions, not just lexical work.

**Comment by ElisaKendall** [comment]
@VladimirAlexiev - I agree with you, so in this particular case, removing the parenthetical comment is better than Pete's suggestion.  There are others where it's more difficult to figure out the right revision - if terms are typically defined based on their extension, meaning, the set of things that can be in the class, then using an 'or' seems like a reasonable approach, And if removing the set of things in the list and moving that to an explanatory note, which I've done in a few cases, leaves a vacuous definition, then is that better? I don't think so.
