### ISSUE TITLE
New hygiene test - circular owl:imports

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1177]
https://github.com/edmcouncil/fibo/issues/1152 shows that FIBO may contain circular owl:imports.

I cannot imagine any reasonable rationale for having those so IMO we should avoid this at least in PROD.

I would thus suggest the following hygiene test - note that it will terminate PROD release when owl:imports are circular there.

```
SELECT DISTINCT ?error ?ontology ?imported_ontology
WHERE
{
    ?ontology owl:imports ?imported_ontology.
    ?imported_ontology owl:imports+ ?ontology.
    FILTER (CONTAINS(str(?ontology), "edmcouncil"))
    FILTER (CONTAINS(str(?imported_ontology), "edmcouncil"))
    BIND (concat ("PRODERROR: ", str(?ontology), " has circular imports to ", str(?imported_ontology)) AS ?error)
}
ORDER BY ?ontology
```

The query will show the circular ontology and all those of its imports that cause import circularity.

**Comment by ElisaKendall** [comment]
Pawel, I cannot get to these immediately, so please do not make this an error yet.  I need to see that other issues pass/fail that are more important, and it will take time to clean them all up.

Dean and I have an agreement that until I can get something to pass, we don't change it from warning to error.  I agree that we should address these, and I've already done some of that, but it will take time to resolve them.

I need to be able to see the other results, and the log is so large that I can no longer take the time to look at it.  That defeats the purpose of having the tests in the first place.  And, if FIBO doesn't pass, then we will never release it.  We cannot release something that doesn't pass at least our very basic tests.

**Comment by mereolog** [comment]
@ElisaKendall What about having a check for direct imports, i.e., for cases when an ontology imports itself?
These should be much fewer and easier to fix.
```
SELECT DISTINCT ?error ?ontology 
WHERE
{
    ?ontology owl:imports ?ontology.
    FILTER (CONTAINS(str(?ontology), "edmcouncil"))
    BIND (concat ("PRODERROR: ", str(?ontology), " imports itself.") AS ?error)
}
```

**Comment by ElisaKendall** [comment]
@mereolog I think the self-imports check is fine and hopefully we won't find any.  Would you please run the broader "all circular imports" test, and attach the results, so I can see what the impact might be?  It's possible that there may not be many in prod (or at least I hope that's the case).

**Comment by mereolog** [comment]
@ElisaKendall I am happy to report that there are no circular imports, be them direct or indirect, in the latest PROD.
