### ISSUE TITLE
New hygiene test - incomplete modeling indicator

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1191]
https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t6-partial-modeling suggests that a class with a single subclass MAY indicate unfinished modeling.

The following query finds all such cases:
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

##
# banner Class with a single subclass may indicate incomplete modeling.

SELECT DISTINCT ?warning ?class2
WHERE 
{

  ?class1 rdfs:subClassOf ?class2 .
  FILTER (ISIRI(?class2))
  FILTER (CONTAINS(str(?class2), "edmcouncil"))
  BIND (concat ("WARN: Class ", str(?class2), " has just one subclass.") AS ?warning)
}
GROUP BY ?warning ?class2
HAVING (COUNT(?class1)=1)
```

See also: https://github.com/edmcouncil/ontology-publisher/issues/20.

**Comment by ElisaKendall** [comment]
Can we find a way to put the output from each test in a separate file, aside from those that we say are ERROR in prod?  This will clutter the results to the degree that I can't sift through them.  I'm sure there are a number of these concepts where we think that FIBO users may extend a given class, but that we have not incorporated.  I would say that the same should be done for the ambiguous definitions, for example.

**Comment by rivettp** [comment]
This doesn't make sense to me at all. Even based on the section in the ontology guide, but I could think about lots of other cases. 
BTW that misuses "singleton" which means a class with a single instance not with a single subclass.
BTBTW I made lots of comments on the Ontology Guide - why don't we firm that up before hardcoding hygiene tests based on it?

**Comment by mereolog** [comment]
As for:

> Can we find a way to put the output from each test in a separate file, aside from those that we say are ERROR in prod? This will clutter the results to the degree that I can't sift through them. I'm sure there are a number of these concepts where we think that FIBO users may extend a given class, but that we have not incorporated. I would say that the same should be done for the ambiguous definitions, for example.

I think this request should go to @przemekgradzki and perhaps be handled  in https://github.com/edmcouncil/ontology-publisher where the issues with our DevOps process are discussed.

**Comment by mereolog** [comment]
As for:

> BTBTW I made lots of comments on the Ontology Guide - why don't we firm that up before hardcoding hygiene tests based on it?

@rivettp, where can I find these comments?
I've just searched for them using github search and was not able to find a single issue there that reports any of them - but I might have missed something.

**Comment by mereolog** [comment]
Shall I then modify the ontology guide so that this test be no longer recommended as a hygiene test candidate?

**Comment by trypuz** [comment]
IMO, a class with a single subclass indicates either unfinished modelling or is a sign of more serious problems. @mereolog, please add this test as WARN.

**Comment by rivettp** [comment]
I disagree @trypuz - to take a real example from a real project - we have class LegalEntity with a single subclass RegulatedEntity which has additional restrictions and properties 9e.g. to regualtions). Are you saying that's unfinished? Has serious problems? Would you also force an additional subclass UnregulatedEntity? IMO that would be wrong from Open World perspective - just because you're not aware of an applicable regulation doesn't mean the entity is unregulated?

**Comment by rivettp** [comment]
FWIW there are over 50 classes in the schema.org class hierarchy with only one subclass.

**Comment by rivettp** [comment]
Further, with FIBO we're trying to be use-case-driven not to provide a complete taxonomic model of the universe. Hence it's quite legitimate not to expand out all possible subclasses. An example of where we went for over-completeness in the past was to model criminal organization (or similar) as part of a complete set of subclasses of organization.

**Comment by mereolog** [comment]
Since this is a rather stale issue now, I going to follow @rivettp view and drop the suggestion of this test from the ontology guide.
