### ISSUE TITLE
Hygiene test clarification inquiry - missing domain or range in properties

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1193]
Could we clarify the meaning of the requirement specified in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t8-missing-domain-or-range-in-properties?

Does this outline some automated hygiene test, like a SPARQL query, or just describe a general modelling principle for domains and ranges of properties?

**Comment by ElisaKendall** [comment]
I think it's a general principle - and in many cases we don't want a domain or range, which makes properties less reusable.

**Comment by rivettp** [comment]
I agree with @ElisaKendall we don't want a hygiene test for this. I don't even know why it's in the candidates except to explicitly reject it as a speciously attractive rule for those coming from a data modeling background.

Reminder: we have a policy against explicitly using Thing and Resource as domain/range.

**Comment by mereolog** [comment]
Shall I then modify the ontology guide so that this test be no longer recommended as a hygiene test candidate?

**Comment by trypuz** [comment]
We could try to check 
- if  "more specific" relations have a domain and/or range. 
- if data properties have a defined datatype in their range.

"More specific" relations could be defined as the ones that are sub-properties of some relations (top property does not count).

**Comment by mereolog** [comment]
@trypuz then this should do the trick for object properties:
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?warning ?property ?parentProperty
WHERE
{
?property rdfs:subPropertyOf ?parentProperty .
FILTER (CONTAINS(str(?property), "edmcouncil"))
FILTER NOT EXISTS {?property rdfs:domain ?domain}
FILTER NOT EXISTS {?property rdfs:range ?range}
BIND (concat ("WARN: object property ", str(?property), " has no domain or range specified although it has a parent property.") AS ?warning)
} 
```
and this for datatype properties:
```
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#> 

SELECT ?warning ?property
WHERE
{
?property rdf:type owl:DatatypeProperty.
FILTER (CONTAINS(str(?property), "edmcouncil"))
FILTER NOT EXISTS {?property rdfs:range ?range}
BIND (concat ("WARN: datatype property ", str(?property), " has no range specified.") AS ?warning)
}
```

**Comment by trypuz** [comment]
@mereolog, thank you. IMO, the warnings they give us is substantial. @ElisaKendall, does the first query (that Pawel presented above) express your intuition concerning "more specific" relations?

**Comment by ElisaKendall** [comment]
@trypuz I think it's 'closer' - we already have a test for crossing domains and ranges.  I think for subproperties we will still need to ignore property chains, and subproperties of property chains, among others.  I have a lot of work to do to reallign some properties with the latest patterns related to situations, which I will do as time permits.  But, I think we need to see what the results are from these queries before making a decision.  Would you please run them for me and send me the output so that I can review and see if there are other refinements we can make to eliminate false positives?

**Comment by rivettp** [comment]
I don't see the rationale for warning about sub properties with no domain or range. Is it even based on the ontology guide? What's the justification or anti-pattern you're trying to guard against?

**Comment by ElisaKendall** [comment]
@rivettp - I don't think we need this unless there are FIBO users complaining.  In fact, I think NOT constraining properties with a domain or range makes them far more reusable, though I also don't see the need for subproperties unless they are further constrained than their superproperties.  So it would be interesting to see the results of the query, which might help us eliminate more unnecessary properties :).

**Comment by ElisaKendall** [comment]
> Shall I then modify the ontology guide so that this test be no longer recommended as a hygiene test candidate?

I think that's a good idea.  This was a naive test in the Oops! tool, and we took our original guidance from them when I wrote the early version of the guide, and the same test was in Stanford's Chimaera tool.  It may provide guidance to modelers, but I am not convinced that we need it, aside from identifying (maybe) properties we don't really need.  The challenge there is that there are lots of properties that are not subproperties of something that are also redundant still ... so I don't know whether or not this is worth bothering with.

**Comment by rivettp** [comment]
Elisa knows this but wanted to clarify for others that she was using "constraining properties" generally (2 comments ago) and that declaring a property p to have a range of C is not a constraint in terms of limiting the values. If I assert triple "X p D" and D is not a member of C, that is not an error - instead it will infer that D is after all a member of C.
