### ISSUE TITLE
Dots in local fragments/resource names of FIBO IRIs

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1198]
It seems to me that https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#naming-and-labeling-conventions does not allow, or at least does not recommend, using dots (fullstops) in the local fragments of IRIs, i.e., in the so called resource names.

Still there is quite a few of those - see: [edmcfibo-QueryResult.xlsx](https://github.com/edmcouncil/fibo/files/5407140/edmcfibo-QueryResult.xlsx).

Some of them may be needed, e.g., '/USD-Federal_Funds-H.15-OIS-COMPOUND', but others look like some unfinished work to me, e.g., 'mayBe.1', 'relatesTo.18', etc. Perhaps, someone wanted to keep unique IRIs and added subsequent integers to the resource names?

Shouldn't we have a hygiene test that finds these?
```
SELECT DISTINCT ?warning ?entity
WHERE 
{
    ?entity ?property ?object
    FILTER (CONTAINS(str(?entity), "edmcouncil"))
    FILTER (CONTAINS(STRAFTER(str(?entity),"https://spec.edmcouncil.org/fibo/ontology/"), "."))
    BIND (concat ("WARN: Resource name of ", str(?entity), " has the dot inside.") AS ?warning) 
}
```
Btw., this is related, although not identical, to https://github.com/edmcouncil/fibo/issues/1119, which IMHO was prematurely closed.

**Comment by ElisaKendall** [comment]
@mereolog - the ones that are "relatesTo.18' etc. are indeed things that we need to address still ... I've been slowly but surely replacing them with existing properties in restrictions, but need to know the domain/range of the "dot property' to do that, so I would not want a blanket removal.

The ones that are in individual names, such as the Fed Funds rate you cited, are generated from the FpML interest rates.  I think we probably don't want a hygiene test for this, since those are correct.  But, as a rule of thumb, we don't want people creating properties with 'dots' in their names.  We could test PROD for object properties and data properties with dots if you want to, but not classes/individuals, especially those that are generated.

**Comment by mereolog** [comment]
@ElisaKendall As far as I know we don't have the infrastructure in place to run some tests for PROD and others for PROD and DEV, etc.
So this test may run either as WARN-level test for everything or as PRODERROR (for everything) - the latter will stop all PROD releases if such properties are found.

**Comment by ElisaKendall** [comment]
@mereolog I think we do run some tests only on PROD, or only make them errors on PROD - you might take a look at the output from any recent pull request and you'll see the distinction.  In any case, I would only want this test on properties I think, not classes/individuals, though maybe individuals that are generated from some reference are the only cases where this occurs consistently.  The H.15 schedule from the Federal Reserve is one of those, but they are all individuals.  The issues in Corporate actions should now be gone if you re-run this, fyi.

**Comment by mereolog** [comment]
@przemekgradzki How can I run a hygiene test only on PROD?

**Comment by przemekgradzki** [comment]
@mereolog as for now it's not possible. See _while..._ loop for [DEV](https://github.com/edmcouncil/ontology-publisher/blob/master/publisher/product/ontology/build.sh#L126) - all hygiene tests are run unconditionally (same as for [PROD](https://github.com/edmcouncil/ontology-publisher/blob/master/publisher/product/ontology/build.sh#L142))

**Comment by mereolog** [comment]
@ElisaKendall given what @przemekgradzki said, shall we run this test as another WARN-level test?

**Comment by ElisaKendall** [comment]
@mereolog - Hi Pawel, if you do that, I would only run it on class names and property names, but not on individual names, since there are legitimate uses of '.', ''-', and '_' (the 3 characters allowable in names other than alphanumeric ascii characters) in some of the individuals.  It would be interesting to see what you get as you are testing it, to see if it actually finds anything in PROD if you exclude individuals.

**Comment by mereolog** [comment]
@ElisaKendall having run the following query against latest PROD I found **no** **properties** with dots in their names:
```
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?warning ?property ?propertyType
WHERE 
{
    ?property rdf:type/rdfs:subClassOf rdf:Property .
    ?property rdf:type ?propertyType .
    FILTER (CONTAINS(str(?property), "edmcouncil"))
    FILTER (CONTAINS(STRAFTER(str(?property),"https://spec.edmcouncil.org/fibo/ontology/"), "."))
    BIND (concat ("WARN: Property ", str(?property), " has the dot in its local name. ") AS ?warning) 
}
```

**Comment by ElisaKendall** [comment]
@mereolog Cool - how about class names?  I'm hoping the only places we'll find these are in DEV.  My latest DER pull request (the one that is sitting out there now) resolves more of those that were in the options ontology, in fact.

**Comment by mereolog** [comment]
No class names with dots as well.
```
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?warning ?resource ?resourceType
WHERE 
{
    {?resource rdf:type/rdfs:subClassOf* rdf:Property .}
    UNION
    {?resource rdf:type/rdfs:subClassOf* rdfs:Class .}
    ?resource rdf:type ?resourceType .
    FILTER (CONTAINS(str(?resource), "edmcouncil"))
    FILTER (CONTAINS(STRAFTER(str(?resource),"https://spec.edmcouncil.org/fibo/ontology/"), "."))
    BIND (concat ("WARN: Resource ", str(?resource), " has the dot in its local name. ") AS ?warning) 
}
```

**Comment by ElisaKendall** [comment]
@mereolog great - so as long as we allow the '.' in individual names, I think we could include this test.  They should not be allowed in class or property names in PROD, and produce warnings in DEV.  I know there are still a number of these out there - takes time to get to them all, and it's not my highest priority at the moment.  But having the test will keep other folks from doing this inadvertently.
