### ISSUE TITLE
Why xsd:anyURI literals instead of real URLs?

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#1200]
- me (from #983 item 17): Please explain why do you use owl:DatatypeProperties with ^^xsd:anyURI instead of real URLs (i.e. owl:ObjectProperties without range).
- @ElisaKendall If you use OWL reasoning, there are certain declarations / uses that disallow a URI in the range. So for annotations we've used anyURI.

Elisa, can you please explain these declarations / uses / restrictions?
- I've wondered for years why people use xsd:anyURI literals instead of real URLs, and haven't found an explanation. 
- It's worth explaining it in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md

I analyzed instances of anyURI in 2020Q3-prod like this:
```
 find . -iname '*.ttl'|xargs cat|riot -syntax ttl -out nt |sort > all.nt
 grep anyURI all.nt |cut -d " " -f2 |sort|uniq -c|sort -rn > anyURI-props.txt
```

A lot are annotation props but not all. Star indicates maybe a change is needed:
```
*  1990 <https://spec.edmcouncil.org/fibo/ontology/FND/Places/VirtualPlaces/hasWebsite>
*   571 <http://www.omg.org/techprocess/ab/SpecificationMetadata/dependsOn>
    479 <https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/adaptedFrom>
*   130 <http://purl.org/dc/terms/license>
*   122 <http://www.omg.org/techprocess/ab/SpecificationMetadata/contentLanguage>
     41 <https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/definitionOrigin>
      4 <http://www.w3.org/2000/01/rdf-schema#seeAlso>
      2 <http://www.w3.org/2000/01/rdf-schema#range>
      1 <https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/AnnotationVocabulary/explanatoryNote>
      1 <http://www.w3.org/2004/02/skos/core#example>
      1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first>
      1 <http://www.omg.org/techprocess/ab/SpecificationMetadata/relatedSpecification>
      1 <http://www.omg.org/techprocess/ab/SpecificationMetadata/directSource>
?     1 <http://purl.org/dc/terms/source>
```

I checked range and the list:
```
 grep anyURI all.nt |grep -E "#range|#first"
```
The following props have range xsd:anyURI:
- <https://spec.edmcouncil.org/fibo/ontology/FND/Places/VirtualPlaces/hasURL> 
- <https://spec.edmcouncil.org/fibo/ontology/FND/Places/VirtualPlaces/hasWebsite>
- <https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/QualifiedMeasure> (string or anyURI, see #933)

**Comment by VladimirAlexiev** [comment]
If the criterion for using anyURI is "does the target have a type" or "does the target have some statements", that's a very brittle criterion and contradicts OWA.

Eg if I add a type and some statements about a website URL (eg using schema.org), does that mean <https://spec.edmcouncil.org/fibo/ontology/FND/Places/VirtualPlaces/hasWebsite> should be an object property?

**Comment by rivettp** [comment]
These are all good points except I don't understand D - it seems that these are declared and used as datatype properties with the anyURI datatype. I don't think it makes sense to try to represent sites as resources for FIBO. And if they were separately modeled as resources I don't see that being a problem either.

**Comment by VladimirAlexiev** [comment]
@rivettp what you describe in D means that FIBO rejects OWA.

-  It's ok for FIBO to decide that website info is out of scope of FIBO, 
- but it's not ok to select a representation such that **nobody** can add info about those websites
