### ISSUE TITLE
Eliminate notions related to transactions in the various lower level derivatives ontologies

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1237]
From SME discussion in the DER working group:  There’s no such thing as a forward transaction, option transaction, etc. They are forward contracts, option contracts, etc. The word “transaction” comes from a processing accommodation. Most trading system do buy/sell etc. transactions. So the easiest way for a trading system to implement derivatives was through transactions rather than establishing the derivative as an asset that itself could be exercised, bought and sold. Using transactions was an easy way to quickly accommodate derivatives but has these drawbacks:

As I alluded to above, if you want to buy or sell a derivative there are plenty of problems if it exists only as a transaction
Changes to derivatives become a problem since you need to start linking transactions
All assets need to be valued. Easy for stocks and bonds but derivatives become a problem when they exist as transactions

Also what you have as the definition is only correct for the transaction that establishes the derivative. There are other derivative transactions. For example, for future contracts there is likely a forward exercise transaction.

You get the idea. “Transaction” also comes about since FpML sends derivative data between parties via messages which most lay people consider to be the same as transactions.

**Comment by ElisaKendall** [comment]
The distinction between an OTC contract and exchange-traded contract is also dubious - many derivatives and certainly swaps must be cleared today, which wasn't necessarily the case when FIBO was originally developed.  The distinctions add unnecessary clutter, however, and should be eliminated.

**Comment by rivettp** [comment]
Not sure how relevant here but we should also ensure we can handle Central Counterparties, which are more prevalent in Europe https://en.wikipedia.org/wiki/Central_counterparty_clearing and officially listed https://www.esma.europa.eu/sites/default/files/library/ccps_authorised_under_emir.pdf

**Comment by ElisaKendall** [comment]
@rivettp We have the concept of a central counterparty clearing house already, although I don't believe we've created the individuals for all CCPs to date

**Comment by rivettp** [comment]
My concern was less whether we have a class for the clearing house entity, but whether we can represent a single trade as both an end-to-end trade between the 2 real parties; and also allow drill into the detail to show it mediated via a specific CCCH. Need an example!
