### ISSUE TITLE
False positives in the test for circular definitions

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1261]
There are cases where the hygiene test for circular references identifies a definition as being circular when it is not.  This happens when the concept in question is a "short form" of other terms used in the definition.  For example, the definition of 'trust' in the BE/Trusts/Trusts ontology is identified as being circular, but the actual definition is:

"fiduciary relationship and legal entity in which one party, known as a trustor, gives another party, the trustee, the right to hold title to and manage assets for the benefit of a third party, the beneficiary"

The term 'trust' does not appear in the definition, but 'trustor' and 'trustee' do, and so the definition is considered circular.  I think we need a work-around that checks for blank spaces or punctuation, e.g., ';', ':', ',', '.', '-'  to determine word boundaries, so that these false positives are eliminated.

**Comment by mereolog** [comment]
Agreed - I will update the test accordingly.
