### ISSUE TITLE
Typo in ontology prefix: fibo-ge-ge-cbj

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#1314]
Pertains to FIBO Production, https://spec.edmcouncil.org/fibo/ontology/master/2020Q4/prod.ttl.zip
File: FIBO\BE\GovernmentEntities\NorthAmericanJurisdiction\CaribbeanGovernmentEntitiesAndJurisdictions.ttl
Line 18: @prefix fibo-**ge**-ge-cbj: <https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/NorthAmericanJurisdiction/CaribbeanGovernmentEntitiesAndJurisdictions/> .

Should be fibo-**be**-ge-cbj

**Comment by ElisaKendall** [comment]
@jziemer2  Nice catch! It is internally consistent, so it wasn't flagged as an error.

**Comment by rdinnik** [comment]
ср, 20 янв. 2021 г., 6:35 Elisa Kendall <notifications@github.com>:

**Comment by jziemer2** [comment]
Welcome, @ElisaKendall,
The ontology to data model transformation process caught it because there was no parent package for cbj_
