### ISSUE TITLE
fibo-fnd-acc-cur:Currency specializes Identifier

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1320]
It can be inferred that fibo-fnd-acc-cur:Currency is a subclass of [LCC's identifier](https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/Identifier):

![image](https://user-images.githubusercontent.com/11171688/106144046-8d99e480-616b-11eb-8caa-e38ff7df2f4a.png)

I feel that this is not correct as currencies do not uniquely identify anything.

The reason for this misclassification is, I think, that [hasNumericCode ](https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/hasNumericCode)property, which describes fibo-fnd-acc-cur:Currency, is a subproperty of [hasTag](https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/hasTag) property, whose domain is [LCC's identifier](https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/Identifier).

Anyway, if this is the correct specialization, perhaps we should make it explicit by adding the appropriate tripe to the ontology.

**Comment by ElisaKendall** [comment]
@mereolog I ran into this recently as well, and corrected the hasNumericCode property such that it is no longer a subproperty of hasTag.  You might want to pull from master and see if the problem has been fixed.

**Comment by mereolog** [comment]
Yes, this is now fixed.
