### ISSUE TITLE
Problematic sources in citations

### ISSUE THREAD

**Issue by kptyson** [edmcouncil/fibo#1321]
You guys have made tremendous progress in cleaning up the sources cited via definitionOrigin.  Checking the current development versions of the ontology and vocabulary I found the following problematic citations.

1. https://spec.edmcouncil.org/fibo/ontology/BP/SecuritiesIssuance/DebtIssuance/AdvancedRefunding 
2. https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/governs
3. https://spec.edmcouncil.org/fibo/FBC/vocabulary#Entitlement
4. https://spec.edmcouncil.org/fibo/FBC/vocabulary#EquityInstrument
5. https://spec.edmcouncil.org/fibo/FBC/vocabulary#Future
6. https://spec.edmcouncil.org/fibo/FBC/vocabulary#Option
7. https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/Entitlement
8. https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/EquityInstrument
9. https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/Future
10. https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/Option
11. https://spec.edmcouncil.org/fibo/FND/vocabulary#confers
12. https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/confers
13. https://spec.edmcouncil.org/fibo/BP/vocabulary#AdvancedRefunding
14. https://spec.edmcouncil.org/fibo/FND/vocabulary#governs

**Comment by ElisaKendall** [comment]
@kptyson Thanks!  I'll keep at it.  The FBC issues are on my list already, as well as cleaning up a few circular definitions in FBC, but I'll try to get to all of those remaining soon.  There are some other references that use adaptedFrom that I want to clean up as well, fyi.  Most of our definitions are fairly different from the sources we referenced in any case - and if there is any value in retaining them, aside from references to ISO specs and government sites, we might use seeAlso in some cases to be clearer.
