### ISSUE TITLE
Correct hygiene issues related to diacritical markings in various government and jurisdiction ontologies

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1333]
There are a few definitions in the BE government and jurisdiction ontologies that include diacritical marks for language-specific names that should be moved to language-specific annotations, flagged by the hygiene testing.

**Comment by jfgemski** [comment]
The official names of some countries do contain diacritical markings (e.g.,  Côte d'Ivoire ). I believe in those cases, the English version should be placed into the language-specific annotations.  Shouldn’t FIBO contain the proper names?  

 

John

 

Jfgemski@gmail.com <mailto:Jfgemski@gmail.com>  | M: (516) 353-0004

**Comment by ElisaKendall** [comment]
@jfgemski Yes, but with the proper language tags.  I won't do all of them in this pass, just the ones that the hygiene testing flagged, but the ones with an English language tag can only contain the diacritics allowed for English ... which includes a few of them, but not all.  So the solution is to add the proper name in that language with the language tags, and to use the official English names from the U.N. for names that are tagged in English.  I sort of combined the two for some countries when I created the original files, which is why the hygiene testing flagged them.
