### ISSUE TITLE
Need to be able to identify a person's place of residence

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1444]
This should be a subproperty of hasAddress, called hasResidence, with a subproperty of hasPrimaryResidence

From IND FCT discussions, one definition of residency is 'A duration of stay required by state and local laws that entitles a person to the legal protection and benefits provided by applicable statutes.' So what we need to determine residency relates to jurisdiction and to where someone resides. Thus having residency is different from having a residence. This initial issue is about having a residence (i.e., dwelling place) rather than residency.

Note that a person can have more than one residence, thus primary residence is also needed for some purposes, such as for mortgages.

**Comment by tahoeblue** [comment]
As you mention, there is are additional considerations for “residency” (versus having a residence) vis-a-vis legal rights (or restrictions) and, in particular, taxation.   

Citizens of one country that reside in another country (e.g., “ex pats”) face a number of different conditions depending on the specific combination of the two jurisdictions (that of citizenship and that of residence).  

Also, “hasPrimaryResidence” is not necessarily restricted to only one instance (e.g. in cases of dual citizenship, etc).  

There are also other (somewhat subtle) considerations with regards to residency and local regulations such as rent-control when it comes to “hasPrimaryResidence”.  

It would seem therefore that “hasPrimaryResidence” should probably have a jurisdictional context rule applied to it.

**Comment by ElisaKendall** [comment]
@tahoeblue I've only added one restriction, on hasResidence, which has a min 0 cardinality, so that a person can have 0 or more residences, and in fact could have multiple primary residences.  I haven't connected the notion of primary residence to jurisdiction, but using a reverse sparql query one could determine the jurisdiction(s) that apply to the address.  

I think jurisdiction is a more complicated issue, though.  We live in Los Altos, so we are subject to city and Santa Clara County laws for various purposes, in addition to the fact that Santa Clara County is in the state of California, in the United States.  But congressional districts, census districts, water districts, transportation districts and likely others also apply.  And a number of those jurisdictions are relevant from a sales tax perspective.  And, my cousin lives half the year in Italy and half the year in Southern California, and that situation definitely complicates things.

For the purposes of this issue, I think we should punt on jurisdiction, though.  We might decide to add something to the address ontology with respect to jurisdiction(s) if we need that for some use cases, but I don't think it belongs in the people ontology.

**Comment by tahoeblue** [comment]
I agree —I was not suggesting that jurisdiction enter the picture at the moment.  It will just need to be considered when “residency” as opposed to “hasResidence” is taken up.  Just comments for the future.
