### ISSUE TITLE
Add Canadian Business Numbers and Tax Accounts

### ISSUE THREAD

**Issue by oldskeptic** [edmcouncil/fibo#1504]
FIBO is currently missing:

* The entity for the taxation authority of the Government of Canada, the Canada Revenue Agency.
* A definition for Business Numbers (BN) that identify business or legal entities. These are different that the tax identifier of a natural person or a corporate registration number.
* Definitions for Corporate, HST (VAT), Import/Export and Payroll Tax accounts, whose numbering scheme is derived from the Business Number. There can be up to 9,999 sub accounts of each type and are used for invoicing/receipts,  tax reporting and accounting.

I'm working on a pull-request to implement these will retaining a logical relationship between the business number and the tax number.

**Comment by trypuz** [comment]
@trojczak is currently working on our serialization tools. @trojczak, please be in touch with @oldskeptic; please assist if needed.

**Comment by trojczak** [comment]
Hello @oldskeptic, here is the latest version of rdf-toolkit:
- https://jenkins.edmcouncil.org/view/rdf-toolkit/job/rdf-toolkit-build/lastSuccessfulBuild/artifact/target/scala-2.12/rdf-toolkit.jar

and here is the lastest version of pre-commit file:
- https://raw.githubusercontent.com/edmcouncil/rdf-toolkit/master/etc/git-hook/pre-commit
