### ISSUE TITLE
Need a restriction on entity ownership indicating the percentage

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1509]
This could belong on ownership or on entity ownership in ownership parties, but it's a gap on the entity ownership class.

**Comment by tahoeblue** [comment]
I’m not sure what other properties are currently defined in the entity ownership class, but this general topic has many variations and dimensions. For example, the distinction between ownership and control, which overlap but are not isomorphic. Second, the distinction between control and economic benefit (e.g., voting shares versus economic shares), which also overlap but are not isomorphic.  Finally, the variations in the forms and mechanisms of ownership and control (e.g., public shares, partnership shares, percentage stipulation, joint ventures, and contractual covenants in which ownership or control  “options” are triggered by a variety of events or conditions).

As only an illustrative example of these considerations, I am attaching some analysis of entity relationships that Craig Layman and Tahoe Blue provided as part of the FSB LEI Private Sector Preparatory Group (PSPG) analysis of the business requirements for the Global LEI System entity relationship workstream back in early 2013.

( This analysis depicts these relationship variations as triples with a scalar measure, hence suitable for representation in RDF* )

Best,

-Jeff

**Comment by ElisaKendall** [comment]
@tahoeblue Hi Jeff,  Totally agree with you about the distinction between ownership and control, and the various methods related to each concept.  We've maintained that distinction in the current representation in FIBO.  Your attachment didn't come through though, so if you would please email it to me, that would be helpful.  This issue is one we ran into at Wells Fargo, where the restriction was missing, so that's why I've raised this issue (and submitted the subsequent fix).
