### ISSUE TITLE
Problem with IS CONTROLLING PARTY IN

### ISSUE THREAD

**Issue by ecow** [edmcouncil/fibo#1537]
In fibo viewer Resource URL:
https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Control/isControllingPartyIn

In last  downloaded quickstart ttl (from https://spec.edmcouncil.org/fibo/ontology/master/2021Q1/prod.fibo-quickstart.ttl) is:
https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Control/isControllingPartyInRole

Is fibo viewer aligned with the last production version?

**Comment by mereolog** [comment]
Default configuration of FIBO viewer shows the latest development version.

If you want to see FIBO as it was at a production release, you should select it in the time machine box as shown below:
![image](https://user-images.githubusercontent.com/11171688/121207443-31f60b00-c871-11eb-9b31-8c1e9e131bd8.png)
('2021Q1' identifies the last release this year - we will release a new version by the end of this month.)

Alternatively you can add suffix '?version=master%2F2021Q1' to the IRI you search, e.g., https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Control/isControllingPartyInRole?version=master%2F2021Q1

**Comment by ecow** [comment]
Thanks.
I agree with the development version (the one in viewer): 
 `[BeneficialOwner]--- isControllingPartyIn -->[BeneficialOwnership]` 
sounds much more better than 
`[BeneficialOwner]--- isControllingPartyInRole -->[BeneficialOwnership]` 
even because BeneficialOwnership is not a Role but a Situation
