### ISSUE TITLE
Need to revise the definition of S&P 500

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1574]
Some details that should be included in a note:

The S&P 500 is calculated by adding each company's float-adjusted market capitalization. In order to be included in the S&P 500, a company must meet certain requirements including achieving a specific market cap, having a majority of its shares in public hands, and being a public company for at least a year.

We need to have a way to specify how the members of a given basket are selected and who does the selection to address this.

**Comment by tahoeblue** [comment]
True, but — for the purpose of deriving, calculating or historically normalizing the value of a composite index, all that is important are the members of the list and the calculation method, not how the organization that governs the members of the list do so ( although that information is certainly of interest)

**Comment by ElisaKendall** [comment]
@tahoeblue - this is mainly to add an explanatory note, although we fixed a couple of other things that came up while we were reviewing what we had said.
