### ISSUE TITLE
Problem with GEOGRAPHIC REGION

### ISSUE THREAD

**Issue by colinbellCA** [edmcouncil/fibo#1586]
Resource URL:
https://www.omg.org/spec/LCC/Countries/CountryRepresentation/GeographicRegion

^ That link seems to 404.  https://www.omg.org/spec/LCC/ is where it sits now w/ explicit RDF https://www.omg.org/spec/LCC/Countries/CountryRepresentation.rdf

Maybe if I had an OMG account it might work.

**Comment by colinbellCA** [comment]
That link is on this page:
https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FCountryRepresentation%2FGeographicRegion

**Comment by ElisaKendall** [comment]
Hi Colin - wow!  This is likely an OMG site issue.  I'll give them a call ASAP to find out what's going on.

**Comment by ElisaKendall** [comment]
Just to follow up, when I use Protege and open the https://www.omg.org/spec/LCC/Countries/CountryRepresentation/ ontology from the URL it does open properly, and I can see the class, GeographicRegion, no problem.  It also opens in Protege when I load the currency codes ontology in FND over the web, which imports not only the country representation ontology but a number of the other LCC ontologies as well.

Can you share a bit more about what you are trying to do?  I wouldn't expect the class itself to have an html page associated with it unless you were using a specific tool that rendered such a thing.  I suspect this is an issue with the FIBO viewer, which doesn't create pages for the ontologies that FIBO imports/reuses, only for those that are defined within FIBO, so it should not provide such a link.

**Comment by colinbellCA** [comment]
Hi @ElisaKendall -- I was trying to do the same thing.  Your confirmation that it was working for you made me need to dig a little deeper.  Looks like my work system has some security monitoring that got in the way silently.

Looks like I'm the first person doing work with ontologies and Protege in the company so... first time the monitoring software had seen that access pattern from that app.

I tried on my personal computer and it worked as I expected (and as you confirmed).  Thank you for your quick response.  I probably would have been banging my head against ontologies silently failing for a long time without your comment.

Thanks,
.cpb
-- 
Colin Bell <inbox@colinbell.ca>
