### ISSUE TITLE
Use of equivalence in custom datatypes causes reasoning issues

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1591]
The use of equivalent class for defining the combined date time and text datatypes can cause reasoning errors when used with rule engines and should perhaps be revised through a comment saying that one would have to eliminate / comment them out or replace the equivalence with a subclass axiom if punning is allowed for the application in question.

**Comment by ElisaKendall** [comment]
This comes up as an error in RDFox, which wants rdfs:subClassOf, but that causes punning, so this may or may not be a real issue, and could be something related to the OWL 2 RL profile or to RDFox rather than to the way custom datatypes are declared.

**Comment by mereolog** [comment]
I endorse - see: https://community.stardog.com/t/reasoning-error-on-defined-datatypes/3177.
