### ISSUE TITLE
Problem with DEBT ONTOLOGY

### ISSUE THREAD

**Issue by MajlindaLlugiqi** [edmcouncil/fibo#1607]
Resource URL:
https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt/

Hi.

I am trying to load FIBO ontology with owlready2, and I am getting this message: 
`owlready2.base.OwlReadyOntologyParsingError: Cannot download 'https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/CreditRatings'!` and I saw on your web page that CreditRatings is 'under developement', but it also is showing this error for others parts as e.g Dept `owlready2.base.OwlReadyOntologyParsingError: Cannot download 'https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt'!` even thought Dept status is 'release'.

Is there anyway to fix it?

Best,
Majlinda

**Comment by ElisaKendall** [comment]
HI Majlinda,

I haven't used this python tool, but it looks very useful.  Are you attemping to load these over the web, or have you downloaded the ontologies directly from github for use with your code?  I guess to assist it would be helpful to understand the call that is failing in your code, and whether or not it always fails, or only in some cases.

If you can share more of those kinds of details with us, that would help.

Best regards,

Elisa
