### ISSUE TITLE
FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies/ fibo-fbc-fct-usjrga:StateGovernmentEntity has invalid restriction

### ISSUE THREAD

**Issue by ubbc** [edmcouncil/fibo#1617]
The ** marked owl:Restriction is nested incorrectly and should be removed 

    <rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&fibo-be-ge-ge;hasJurisdiction"/>
				<owl:someValuesFrom>
					<owl:Restriction>
						<owl:onProperty rdf:resource="&fibo-fnd-law-jur;hasReach"/>
						<owl:someValuesFrom>
							**<owl:Restriction>**
								<owl:intersectionOf rdf:parseType="Collection">
									<rdf:Description rdf:about="&lcc-cr;CountrySubdivision">
									</rdf:Description>
									<owl:Restriction>
										<owl:onProperty rdf:resource="&lcc-cr;isSubregionOf"/>
										<owl:hasValue rdf:resource="&lcc-3166-1;UnitedStatesOfAmerica"/>
									</owl:Restriction>
								</owl:intersectionOf>
							**</owl:Restriction>**
						</owl:someValuesFrom>
					</owl:Restriction>
				</owl:someValuesFrom>
			</owl:Restriction>
    </rdfs:subClassOf>

**Comment by mereolog** [comment]
@ubbc could you elaborate on why you find the nested restriction incorrect?

**Comment by ubbc** [comment]
Yes of course, I'll try to.
I believe the expression modelled is:

````
has jurisdiction some (
    has reach some (
        country subdivision and (
            is a subregion of value United States of America (the)
        )
    )
)
````  
in FSS
````
ObjectSomeValuesFrom(
    fibo-be-ge-ge:hasJurisdiction
    ObjectSomeValuesFrom(
       fibo-fnd-law-jur:hasReach (
       ObjectIntersection(
           lcc-cr:CountrySubdivision
           ObjectHasValue(
              lcc-cr:isSubregionOf
              lcc-3166-1:UnitedStatesOfAmerica
           }
       )
   }
}
````
Following [https://www.w3.org/TR/owl2-mapping-to-rdf/](https://www.w3.org/TR/owl2-mapping-to-rdf/) gives

```
[ 
   rdf:type           owl:Restriction ;
   owl:onProperty     fibo-be-ge-ge:hasJurisdiction ;
   owl:someValuesFrom [
                         rdf:type owl:Restriction
                         owl:onProperty     fibo-fnd-law-jur:hasReach ;
                         owl:someValuesFrom [
                                               rdf:type owl:Class ;
                                               owl:intersectionOf (
                                                                    :CountrySubdivision 
                                                                    [
                                                                            rdf:type owl:Restriction ;
                                                                            owl:onProperty :subRegionOf ;
                                                                            owl:hasValue :united_states
                                                                    ]
                                                                  )
                                            ]
                      ]  
]
```

Note that there are 3 Restrictions, not 4,  and the intersection node should be of type owl:Class.

The canonical parser should not ( I think according to 3.2.4 ) parse what you have. 
It's easy to make mistakes - so please forgive me if I have missed something obvious.

**Comment by mereolog** [comment]
No, I can see it too.
Good catch, thanks.

**Comment by ElisaKendall** [comment]
@ubbc I'm certain this has been there for ages - well done.  Hopefully you won't find too many more like this, but in addition to our hygiene testing, etc., I'm starting to use rules with tools like RDFOx to find things that Protege and loading in basic graph databases haven't uncovered to date.
