### ISSUE TITLE
DER/DerivativesContracts/Options/ fibo-fbc-fi-fi:Option has an invalid restriction

### ISSUE THREAD

**Issue by ubbc** [edmcouncil/fibo#1618]
A single restriction is not permitted to contain both a some values restriction and a cardinality restriction.
I suspect thisshould be a cardinality onClass restriction.

    <rdfs:subClassOf>
			<owl:Restriction>
				<owl:onProperty rdf:resource="&fibo-der-drc-opt;hasCalculatedMarketValue"/>
				<owl:minQualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">0</owl:minQualifiedCardinality>
				<owl:someValuesFrom rdf:resource="&fibo-der-drc-opt;OptionPremium"/>
			</owl:Restriction>
    </rdfs:subClassOf>

**Comment by mereolog** [comment]
I think that this is a left-over from some cleaning activity in the past where owl:minQualifiedCardinality was replaced by owl:someValuesFrom as specified in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#minimal-compliance-hygiene-tests.
So I would say that in this case <owl:minQualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">0</owl:minQualifiedCardinality> should be removed.
@ElisaKendall what do you think?

**Comment by ElisaKendall** [comment]
> I think that this is a left-over from some cleaning activity in the past where owl:minQualifiedCardinality was replaced by owl:someValuesFrom as specified in https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#minimal-compliance-hygiene-tests. So I would say that in this case <owl:minQualifiedCardinality rdf:datatype="&xsd;nonNegativeInteger">0</owl:minQualifiedCardinality> should be removed. @ElisaKendall what do you think?

I'm guessing it is the reverse - we likely added the min 0 cardinality because the computed value wasn't always available, but I forgot to change the someValuesFrom to onClass - I've corrected it in any case.
