### ISSUE TITLE
FND/MarketIndices/BasketIndices/hasSharesOutstandingForIssuer is assigned to an invalid property chain

### ISSUE THREAD

**Issue by ubbc** [edmcouncil/fibo#1619]
The `hasSharesOutstandingForIssuer` object property is asserted as the as the (object) property chain:
`FND/Relations/Relations/appliesTo`
`SEC/Equities/EquityInstruments/hasSharesOutstanding`

However, `SEC/Equities/EquityInstruments/hasSharesOutstanding` is asserted as data property and thus this creates an illegal pun.

**Comment by mereolog** [comment]
We can use the following query to monitor all such cases:
```
SELECT ?property
WHERE
{
    ?resource owl:propertyChainAxiom ?axiom.
    ?axiom rdf:rest*/rdf:first ?property .
    FILTER NOT EXISTS {?property rdf:type owl:ObjectProperty}
}
```
At the moment it just finds hasSharesOutstanding in the whole Dev.

**Comment by ElisaKendall** [comment]
@merelog It is possible that we changed some of these properties in the Equities ontology and didn't realize that they were being used in IND in a different way, but it is also possible that the semantics were never right in the first place.  I'll dig in and see what really needs to be done to correct this.  We have an IND call on Friday morning and can work on it then.

Should we add this as a new hygiene test?
