### ISSUE TITLE
Illegal punning for hasConversionRatio 

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1628]
[fibo-der-drc-raw:hasConversionRatio](https://spec.edmcouncil.org/fibo/ontology/DER/DerivativesContracts/RightsAndWarrants/hasConversionRatio) is a sub property of an object property (fibo-fnd-qt-qtu:hasFactor) and a datatype property (fibo-fnd-qt-qtu:hasNumericValue):
```
<owl:DatatypeProperty rdf:about="&fibo-der-drc-raw;hasConversionRatio">
<rdfs:subPropertyOf rdf:resource="&fibo-fnd-qt-qtu;hasFactor"/>
<rdfs:subPropertyOf rdf:resource="&fibo-fnd-qt-qtu;hasNumericValue"/>
<rdfs:label xml:lang="en">has conversion ratio</rdfs:label>
<rdfs:domain rdf:resource="&fibo-fbc-fi-fi;Entitlement"/>
<rdfs:range rdf:resource="&xsd;decimal"/>
<skos:definition xml:lang="en">indicates the factor used to determine the number of warrants needed in order to buy or sell a specific number of securities or investment units</skos:definition>
	</owl:DatatypeProperty>
```
This qualifies fibo-der-drc-raw:hasConversionRatio as illegal punning, so we should decide on its proper type.

Note that this makes [PR-1627](https://github.com/edmcouncil/fibo/pull/1627) to terminate - see: https://jenkins.edmcouncil.org/blue/rest/organizations/jenkins/pipelines/fibo/branches/PR-1627/runs/1/nodes/19/steps/47/log/?start=0

**Comment by ElisaKendall** [comment]
@merelog - fixed, but this is in a provisional ontology and shouldn't cause the process to terminate ??

**Comment by mereolog** [comment]
In general, I agree with @ElisaKendall, but in this particular case there was just one fix needed and after the fix we have a stronger suite of tests that would block further issues like this one in both dev and prod.
