### ISSUE TITLE
Update for catalog-v001.xml - add ontologies from etc/imports

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1647]
ontology-publisher expects that all ontologies it processes:
1. be accessible in some folder within in https://github.com/edmcouncil/fibo
2. be registered as such in [catalog-001.xml](https://github.com/edmcouncil/fibo/blob/master/catalog-v001.xml)

Currently [catalog-001.xml](https://github.com/edmcouncil/fibo/blob/master/catalog-v001.xml) does not register the ontologies stored in https://github.com/edmcouncil/fibo/tree/master/etc/imports.
I think we should add them to [catalog-001.xml](https://github.com/edmcouncil/fibo/blob/master/catalog-v001.xml).

**Comment by ElisaKendall** [comment]
@mereolog I'm not sure that's appropriate, or something we want to do.  It means that every time those ontologies are updated by an external authority, we will need to re-commit them and manage them ourselves.  We don't do that with the 240 LCC ontologies, why would we do so with specification metadata and skos?

**Comment by mereolog** [comment]
I agree that in general this kind of management may be expensive and should be avoided.
The reason for the proposal was to guard off possible interruptions in the import mechanism. The tradeoff here is that ontology-publisher sometimes encounters a glitch when it cannot get the imported ontologies from the internet - sometimes there is a problem within our infrastructure, but sometimes it is "them".

Anyway if we can accept these situations, i.e., when continuous integration process is interrupted or terminated because of the import problems, there is no need to version-control for these ontologies. But in this case I would suggest removing the https://github.com/edmcouncil/fibo/tree/master/etc/imports folder as its being there may be confusing.

**Comment by ElisaKendall** [comment]
@mereolog That makes sense to me.
