### ISSUE TITLE
Named individuals should be eliminated from the hygiene test checking for deprecated individuals still in use

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1675]
Recent revisions to the FpML reference interest rates, which are defined in the CommonInterestRates ontology, include deprecated individuals that were, in fact, deprecated in FpML in the 2021 revision.  As a consequence, we get many warnings about deprecated concepts still in use, but in fact these deprecations come from the source for the reference data.

This is in stark contrast to the point of the warning, which is to let FIBO users know when we have deprecated a concept or property that is likely to be eliminated in a subsequent release.

**Comment by mereolog** [comment]
We can indeed exclude them, but this issue made me thinking about having a new level of messages, like info.

I am thinking about a couple of queries that would, for example, count the number of classes, individuals, properties, etc., and perhaps report the number of deprecated resources as well. We can then send info message about particular deprecated resources by their types, i.e., deprecated classes, individuals, etc.

**Comment by ElisaKendall** [comment]
This makes sense to me.  I'm wondering if having them all displayed as part of the output in the same "Errors in Prod" window makes sense, or if it makes more sense to save them in a log file that gets attached somehow to the github resolution when it is merged or something like that.  I tend to go back and review errors / warnings against closed issues from time to time, so I don't want them to go away entirely, but maybe we need to have a log of all remaining warnings and info messages linked to something we can find easily without having to go look in older issues.  If you have some ideas about that I'm all ears.

**Comment by mereolog** [comment]
@przemekgradzki is this technically feasible? That is, can we somehow send the log file from Jenkins back to GitHub pull request?

**Comment by rivettp** [comment]
The deprecation does have the intended meaning - those indexes are likely to be removed, whether or not it's our decision or FpML's.

**Comment by przemekgradzki** [comment]
Adding a new file to pull request means modifying it, and thus rebuilding it and generating a new log file, which should be added again as a file to PR - a vicious circle is created.

It is possible to perform the action [Upload asset files to a GitHub Release.](https://medium.com/@systemglitch/continuous-integration-with-jenkins-and-github-release-814904e20776), but this is only for Releases.

The easiest solution would be to add comments to pull requests containing links to logs using the [Adding a comment](https://github.com/jenkinsci/pipeline-github-plugin#adding-a-comment) functionality.
