### ISSUE TITLE
Wrong dateTime in MetadataSECDebt

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1684]
[MetadataSECDebt](https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MetadataSECDebt) has the wrong date in the dct:issued property:
<owl:Ontology rdf:about="https://spec.edmcouncil.org/fibo/ontology/SEC/Debt/MetadataSECDebt/">
[...]
<dct:issued rdf:datatype="&xsd;dateTime">2022-02-31T18:00:00</dct:issued>

**Comment by ElisaKendall** [comment]
@mereolog This actually isn't a bug - it will be correct for the Q1 2022 release.

**Comment by mereolog** [comment]
I meant that the month February in 2022 has only 28 days not 31 as stated above: 2022-02-**31**T18:00:00.

**Comment by ElisaKendall** [comment]
oops 🙂
________________________________
