### ISSUE TITLE
Augment the concept of a payment schedule to include those elements needed for ILDR reporting

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1713]
Currently we are missing several required terms, including but not limited to:

Payment amount
Last payment date
Next due date
Number of payments in contract

There are other concepts needed to cover the ILDR reporting requirements, but these are the ones specific to payment schedules.  See the attached mapping from FIBO to the ILDR reporting requirements, which defines these properties.  They are relevant to many debt instruments so should likely be added in FBC to the Debt ontology or possibly be related to Debt instruments.

Note that we should review the concepts in the parametric schedules ontology in SEC and consider whether they should be merged into financial dates for use in payment and other schedules more generally.  Parametric Schedules is a small ontology but important, and some of the concepts defined in that ontology apply more broadly to debt instruments and loans.  Others may be specific to debt instruments such as bonds, and could be retained in their original location.

[FIBO-ILDR Mapping.xlsx](https://github.com/edmcouncil/fibo/files/7967156/FIBO-ILDR.Mapping.xlsx)
[FIBO-ILDR Mapping.xlsx](https://github.com/edmcouncil/fibo/files/7972549/FIBO-ILDR.Mapping.xlsx) - updated during our FIBO SEC call on 1/31/2022

**Comment by rivettp** [comment]
I'm not so keen on "last payment" and "next payment" which are relative to current date - which you'd also need to record. If we have a schedule with dates, and actual payments with dates, then it is easy to calculate last and next from any given current date.
