### ISSUE TITLE
Wording for precious metals currency identifiers needs work

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#1721]
It's nonsense to say "one troy ounce of the ...identifier". It should be something like "identifier for the currency whose unit is one troy ounce of the precious metal silver".  Or could just leave the troy ounce aspect to the Currency definition.
Same for the other identifiers.

_Originally posted by @rivettp in https://github.com/edmcouncil/fibo/pull/1717#discussion_r798198156_

**Comment by ElisaKendall** [comment]
@rivettp These definitions occur in the downloaded codes from ISO and so they need to be overridden in our processing algorithms.  Same for the upper case labels.
