### ISSUE TITLE
Create custom datatypes for currencies

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#1763]
(copy of FND-361)
This would supplement not replace the current currencies and codes, but would allow the use of simple triples for monetary values.
At the moment we have to represent amounts as an individual consisting of value and currency. And either have to coin a URI or use a blank node. Neither very desirable.
 
For example: 
<fibo-fnd-acc-b="&fibo-der-rtd-irsind;ContractLeg1-IY7VKEUR45886-NotionalAmount"/>
  
<owl:NamedIndividual rdf:about="&fibo-der-rtd-irsind;ContractLeg1-IY7VKEUR45886-NotionalAmount">
<rdf:type rdf:resource="&fibo-fnd-acc-cur;MonetaryAmount"/>
<rdfs:label>contract leg 1 IY7VKEUR45886 notional amount</rdfs:label>
<fibo-fnd-acc-cur:hasAmount rdf:datatype="&xsd;decimal">1286805</fibo-fnd-acc-cur:hasAmount>
<fibo-fnd-acc-cur:hasCurrency rdf:resource="&fibo-fnd-acc-4217;Euro"/>
</owl:NamedIndividual>
  
Or, more concisely using a blank node and omitting the label:
 <fibo-fnd-acc-cur:hasNotionalAmount>
     <rdf:type rdf:resource="&fibo-fnd-acc-cur;MonetaryAmount"/>
     <fibo-fnd-acc-cur:hasAmount rdf:datatype="&xsd;decimal">1286805</fibo-fnd-acc-cur:hasAmount>
     <fibo-fnd-acc-cur:hasCurrency rdf:resource="&fibo-fnd-acc-4217;Euro"/>
</fibo-fnd-acc-cur:hasNotionalAmount>
 
I was looking here https://patterns.dataincubator.org/book/custom-datatype.html and wondered whether we could use the custom datatype approach for currency values which would be far more concise and efficient
 
<fibo-fnd-acc-cur:hasNotionalAmount rdf:datatype="&fibo-fnd-acc-4217;EuroAmount">1286805</fibo-fnd-acc-cur:hasNotionalAmount>
 
So that would mean we would declare a datatype for each currency. In addition to the current individual:
 
<owl:NamedIndividual rdf:about="&fibo-fnd-acc-4217;Euro">
<rdf:type rdf:resource="&fibo-fnd-acc-cur;Currency"/>
<rdfs:label>Euro</rdfs:label>
<skos:definition>the currency Euro</skos:definition>
<fibo-fnd-acc-cur:hasMinorUnit>2</fibo-fnd-acc-cur:hasMinorUnit>
<fibo-fnd-acc-cur:hasNumericCode>978</fibo-fnd-acc-cur:hasNumericCode>
<lcc-cr:isUsedBy rdf:resource="&lcc-3166-1;AlandIslands"/>
<lcc-cr:isUsedBy rdf:resource="&lcc-3166-1;Andorra"/>
 
We would add the following triple to Euro above using an annotation property to link the individual to the datatype used for expressing values in it:    <dct:hasFormat rdf:resource="&fibo-fnd-acc-4217;EuroAmount"/>

and then also have:
<rdfs:Datatype rdf:about="&fibo-fnd-acc-4217;EuroAmount">
    <rdfs:label>Euro amount</rdfs:label>
    <rdfs:subClassOf rdf:resource="&fibo-fnd-acc-cur;MoneyAmount>
    <skos:definition>datatype for expressing amounts in the currency Euro</skos:definition>
        
and generically
 <rdfs:Datatype rdf:about="&fibo-fnd-acc-cur;MoneyAmount">
    <rdfs:label>money amount</rdfs:label>
    <rdfs:subClassOf rdf:resource="&xsd;decimal/>
     <skos:definition>datatype for expressing an amount of money </skos:definition>

It's largely additive so in principle would not have a huge impact except that to take full advantage we'd need to change lots of ObjectProperties to DatatypeProperties, so maybe make that last step a FIBO 2.0 thing? Or we could introduce the datatype properties with different URIs in parallel.

**Comment by VladimirAlexiev** [comment]
Hi @rivettp,
would you mind fixing your examples, using backticks, and ideally converting to Turtle to make them easier to read?

So an amount would be represented like this, right?
```ttl
"12.34"^^fibo-fnd-acc-4217:EuroAmount
```

One problem is that major repositories wouldn't know what to do with such datatypes, so eg this won't work:
```sparql
bind("12.34"^^fibo-fnd-acc-4217:EuroAmount + "56.78"^^fibo-fnd-acc-4217:EuroAmount as ?amount)
```
I don't even know whether SPARQL mandates implementing `+` over subtypes of `xsd:decimal`, but I'm pretty sure all major repositories support only XSD.

So you'd need to write 
```sparql
bind(strdt(str(xsd:integer(?a1)+xsd:integer(?a2)),fibo-fnd-acc-4217:EuroAmount) as ?amount)
```
Which is much uglier. (And that's assuming you've already checked the datatypes of `?a1,?a2`!)

Following https://github.com/edmcouncil/fibo/issues/1816, I'd strongly urge to use ISO currency codes in the URL, else you make conversion from datasets that use those codes to RDF, unnecessarily complicated.
So, something like this:
```ttl
"12.34"^^fibo-fnd-acc-4217:EUR
```

Finally, is there a huge amount of harm punning the individual and the datatype? (ok, just being provocative here)

**Comment by mereolog** [comment]
@rivettp this issue is almost one year old. Where are we with this?
