### ISSUE TITLE
fibo-fbc-fct-bci:Alma-ata should be owl:sameAs fibo-fbc-fct-bci:Almaty

### ISSUE THREAD

**Issue by hroptatyr** [edmcouncil/fibo#1781]
Hi, not sure if edmconnect or github is preferred.

I'm aligning FpmL business centres (or FIBO's BusinessCenterIndividuals) with geonames.

I'm pretty sure the distinction between fibo-fbc-fct-bci:Alma-ata (the old name of the city) and fibo-fbc-fct-bci:Almaty is superfluous.  The Kazakh SSR dissolved some 30 years ago.

**Comment by ElisaKendall** [comment]
@hroptatyr Hi Sebastian - GitHub is the right place for this.  But, the names in the business centers ontology come from ISO - we generate them based on the published content in the ISO MIC codes (SO 10383) that are updated monthly.  One option would be to raise an issue with the ISO working group, which I think is TC 68, but I'll reach out to our OMG liaison to make sure we send the issue to the right people.  We can leave this open until we see that the issue has been addressed by ISO, or make the change in our processing of the ISO documents, but the latter approach would mean that we have do check every time to see if they have fixed it and if not, remove it explicitly in our processing code.  My preference is that ISO fix it.

**Comment by hroptatyr** [comment]
Hi Elisa, thanks for getting back.  I got into touch with them myself, outlining the problem and pitching a solution.  For the time being, I used your namespace to create a cleaned up and aligned dataset (it's in my iso10383/ repo).

The new format contains LEIs as well, so for everyone interested it's quite easy to get an independent opinion about the CITY field using linked data from, say, gleif.org via the provided LEI.

**Comment by ElisaKendall** [comment]
Hi Sebastian,

Thanks again for letting us know.  We would love to hear more about what you are doing at some point - would you be interested in presenting to our working group?  We also discussed overriding what is in the ISO codes, but definitely hope ISO will correct their data rather than us having to fix it every time we re-run the generation.  Pete added an override moments ago, so next time we generate the MIC codes, the old Alma-ata city name will be removed, however.

We're happy to hear that you were able to use our reference data, regardless, and that you've mapped it to the LEI data.  

Thanks again,

Elisa

**Comment by hroptatyr** [comment]
Hi Elisa,
I'd certainly be up for a presentation even though it probably looks like nitpicking.

ISO is not a fan of my idea (using UN/LOCODE to encode the city), for one outside of midstream/transport/logistics nobody is aware of UN/LOCODE, and for another it's not made exactly for this purpose.

The "mapping" to LEI is more of reference. However, it is entirely ISO's work, that's what their new MIC data set structure is all about (probably another reason to refrain from changing it again just for the city names).

**Comment by VladimirAlexiev** [comment]
#1816 also discusses `owl:sameAs` and I argued to put such statements in a separate file.

@hroptatyr Your work is now merged into https://github.com/ga-group/iso10383, right? I'll provide some feedback.

Cheers!
