### ISSUE TITLE
Inactive hyperlinks in annotation properties

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1797]
As of 2022 Q2 release FIBO Prod annotation properties contain a number of inactive hyperlinks - they _now_ either refer to a non-existing page (404 error) or to an outdated resource (irrelevant) or currently a more adequate reference can be found (unprecise).

I think we should rectify at least the 404 hyperlinks - if possible; otherwise they probably should be removed at our earliest convenience.

The attached file contains the list of such inactive hyperlinks - together with tentative updates.

[dead_link_analysis 20220713.xlsx](https://github.com/edmcouncil/fibo/files/9102564/dead_link_analysis.20220713.xlsx)

**Comment by ElisaKendall** [comment]
The link issues in FND have been addressed in pull request #1804.

**Comment by ElisaKendall** [comment]
As of 8/7/2022, the links in FND and BE have been addressed, but there are remaining issues in FBC, IND, and SEC links
