### ISSUE TITLE
Problem with ORGANIZATIONS ONTOLOGY

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#1846]
Resource URL:
https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/Organizations/

More errors:

![more_errors](https://user-images.githubusercontent.com/6771512/200780220-4310b57d-095a-4373-a851-02f6c2095c6b.png)

**Comment by mereolog** [comment]
See: https://github.com/edmcouncil/fibo/issues/1845#issuecomment-1308413614.
