### ISSUE TITLE
Issue Loading FIBO Ontology (possible dup of #1607)

### ISSUE THREAD

**Issue by gr-fl** [edmcouncil/fibo#1847]
Hi all & thanks for any help anyone can give.

I'm working with the `owlready2` package and trying to run the FIBO version of this:
https://owlready2.readthedocs.io/en/v0.37/intro.html#short-example-what-can-i-do-with-owlready
```
from owlready2 import *
 o = get_ontology('https://spec.edmcouncil.org/fibo/ontology/FBC/DebtAndEquities/Debt.rdf')
o.load()
```
## Trying to use a URL for FIBO:
I get the following exception after the last line of this sample runs:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/pyenvs/myenv/lib/python3.6/site-packages/owlready2/namespace.py in load(self, only_local, fileobj, reload, reload_if_newer, url, **args)
   1050         if _LOG_LEVEL: print("* Owlready2 *     ...loading ontology %s from %s..." % (self.name, f), file = sys.stderr)
-> 1051         try:     fileobj = urllib.request.urlopen(url or f)
   1052         except:  raise OwlReadyOntologyParsingError("Cannot download '%s'!" % (url or f))

~/pyenvs/myenv/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 

~/pyenvs/myenv/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 

~/pyenvs/myenv/lib/python3.6/urllib/request.py in http_response(self, request, response)
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 

~/pyenvs/myenv/lib/python3.6/urllib/request.py in error(self, proto, *args)
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 

~/pyenvs/myenv/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:

~/pyenvs/myenv/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 

HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

OwlReadyOntologyParsingError              Traceback (most recent call last)
<ipython-input-3-22764c73482e> in <module>
----> 1 o.load()

~/pyenvs/myenv/lib/python3.6/site-packages/owlready2/namespace.py in load(self, only_local, fileobj, reload, reload_if_newer, url, **args)
   1109 
   1110     # Load imported ontologies
-> 1111     imported_ontologies = [self.world.get_ontology(self._unabbreviate(abbrev_iri)).load() for abbrev_iri in self.world._get_obj_triples_sp_o(self.storid, owl_imports)]
   1112     self._imported_ontologies._set(imported_ontologies)
   1113 

~/pyenvs/myenv/lib/python3.6/site-packages/owlready2/namespace.py in <listcomp>(.0)
   1109 
   1110     # Load imported ontologies
-> 1111     imported_ontologies = [self.world.get_ontology(self._unabbreviate(abbrev_iri)).load() for abbrev_iri in self.world._get_obj_triples_sp_o(self.storid, owl_imports)]
   1112     self._imported_ontologies._set(imported_ontologies)
   1113 

~/pyenvs/myenv/lib/python3.6/site-packages/owlready2/namespace.py in load(self, only_local, fileobj, reload, reload_if_newer, url, **args)
   1050         if _LOG_LEVEL: print("* Owlready2 *     ...loading ontology %s from %s..." % (self.name, f), file = sys.stderr)
   1051         try:     fileobj = urllib.request.urlopen(url or f)
-> 1052         except:  raise OwlReadyOntologyParsingError("Cannot download '%s'!" % (url or f))
   1053         #try:     new_base_iri = self.graph.parse(fileobj, default_base = self._base_iri, **args)
   1054         #finally: fileobj.close()

OwlReadyOntologyParsingError: Cannot download 'https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/LegalEntities/LegalPersons'!
```
...the relevant part of which is likely
```
HTTPError: HTTP Error 404: Not Found
```
As it seems the `owlready2` library can't find the dependent `LegalPersons` rdf file for `Debt`.
Since the library is able to obtain the initial `Debt.rdf` file, I don't think this is a proxy issue (in fact, if I turn off the corporate proxy settings I have, it stops working and fails to pull the `Debt.rdf` file because of an SSL exception 😄 ).

## Trying it locally
I also tried doing the equivalent of this locally to cut around any network issues by downloading the `prod.rdf.zip` file from [here](https://edmconnect.edmcouncil.org/fibointerestgroup/fibo-products/fibo-owl), then unzipping the archive and loading it this way:
```
from owlready2 import * 
o = get_ontology('fibo/ontology/master/2022Q3/FBC/DebtAndEquities/Debt.rdf')
o.load()
```
But I get the same exception as loading over a URL, as it appears the local rdf files still reference dependencies remotely, via URL.

[Edit]: Also tried using the `dev.rdf.zip` download, same class of error (unable to find remote dependency).

Anyone have any ideas?

**Comment by mereolog** [comment]
I am not an expert on owlready2 - coding in Python I rather use rdflib.
But it looks as if owlready2 truncates the import object in the following triple:
https://github.com/edmcouncil/fibo/blob/7d326d31c5060c39508a40bff2ebead232ccc308/FBC/DebtAndEquities/Debt.rdf#L76
Instead of taking the proper value:
`https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons/`
it truncates it to:
`https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons`
Now the problem is that only the former resolves and owlready2 tries to import the latter.

It looks to me like an owlready2 issue - I looked briefly in the code and noticed that it does quite a lot of string manipulation on '#' and '/', which usually creates problems. Because there is quite of lot of string substitutions, replacements, etc. I was not able to pin down the problem, but it may be in this method:

```
def _get_onto_file(base_iri, name, mode = "r", only_local = False):
  if base_iri.endswith("#") or base_iri.endswith("/"): base_iri = base_iri[:-1]
  if base_iri.startswith("file://"): return urllib.parse.unquote(base_iri[7:])
  
  for dir in onto_path:
    filename = os.path.join(dir, base_iri.rsplit("/", 1)[-1])
    if os.path.exists(filename): return filename
    for ext in ["", ".nt", ".ntriples", ".rdf", ".owl"]:
      filename = os.path.join(dir, "%s%s" % (name, ext))
      if os.path.exists(filename): return filename
  if (mode.startswith("r")) and not only_local: return base_iri
  if (mode.startswith("w")): return os.path.join(onto_path[0], "%s.owl" % name)
  raise FileNotFoundError
```
If base_iri is https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons/, then the second line in this method truncates it into 'https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons', which eventually leads to the import problem.

**Comment by gr-fl** [comment]
I think you might be right, I will dig around on the `owlready2` page to see if I can find a workaround. Thanks for pointing that out...

Separately , to get around this issue, I tried to explicitly use a version-ed cut of FIBO (e.g, 2022Q1) thinking this might negate the need for the `owlready2` library to follow redirects...
```
https://spec.edmcouncil.org/fibo/
   ...: ontology/master/2022Q1/FBC/DebtAndEquities/Debt/Debt
```
Unfortunately, even when I pull down this version I still see the references from each RDF file pointing to master, suggesting FIBO's "versioning" is only a top-level version and doesn't apply to children, which still pull from master....am I mistaken?

**Comment by gr-fl** [comment]
Separate question, is there a cut of the FIBO RDF structure that uses local/relative references instead of remote ones?

**Comment by ElisaKendall** [comment]
@gr-fl  In GitHub there is an XML catalog that is relative that we use to load FIBO in Protege, for example. I'm not sure that the catalog is included in the zip files available from the release site on the spec.edmcouncil.org. But maybe you could look at the catalog file, called catalog-001.xml to see what that mapping looks like and do something programmatically?

**Comment by mereolog** [comment]
> Separate question, is there a cut of the FIBO RDF structure that uses local/relative references instead of remote ones?

No, there is not.

However we produce something that is called quick version of FIBO, which is a single ontology file with no imports and which aggregates all FIBO ontologies. You can get this following the 'Download' link from https://spec.edmcouncil.org/fibo/page/owl.
