### ISSUE TITLE
Increase coverage and mapping ability for relating FIBO to the FFIEC NIC repository

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#1850]
This issue arose from a requirement from DARPA to map FIBO to the NIC repository in as high fidelity as possible.

Here is the NIC data dictionary: https://www.ffiec.gov/nicpubweb/content/DataDownload/NPW%20Data%20Dictionary.pdf

**Comment by rivettp** [comment]
Obviously at least part of this will need to be jurisdiction-specific e.g. the data dictionary includes the following

> The term bank does NOT include the following types of institutions:
> (a) A bank organized under the laws of a foreign country and resident outside the legal
> boundaries of the United States, even if the bank has a U.S. presence

Maybe this would be a good opportunity to model the terms in their dictionary using MVF.

**Comment by ElisaKendall** [comment]
@rivettp Yes - the repository itself is defined in the NorthAmericanEntities module in FBC, but there may be some general bits and pieces that we would elevate.
