### ISSUE TITLE
Update of FIBO viewer config files

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#1883]
Due to the recent and upcoming changes related to the metadata spec replacements we need to update the FIBO viewer config files.

**Comment by ElisaKendall** [comment]
@merelog - Please include the abstract (now dct:abstract) for the ontologies when you do this - I didn't see it in a quick review. Dependencies on specification metadata should go away, but you might do a scan for replacements, such as dct:contributor.
