### ISSUE TITLE
No prefixes in quickstart.ttl

### ISSUE THREAD

**Issue by peio** [edmcouncil/fibo#1892]
Dear FIBO team, 
 In the last year of releases the list of the prefixes have been removed from the fibo-quickstart distribution. From user's perspective this is very uncomfortable in the mapping and querying processes. Is there an obvious solution, which I am missing or this is an intended effect?

Thank you for all your efforts!
Peio

**Comment by mereolog** [comment]
This will be taken care by means of https://github.com/edmcouncil/ontology-publisher/issues/137.

**Comment by mereolog** [comment]
DEV should have the prefixes now, PROD will get them in the next release.
