### ISSUE TITLE
rework Crunchbase example to latest revisions of FIBO

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#2008]
This is a really great example. Any chance we can update it to use the latest revisions to FIBO, including migration of some ontologies to the OMG's Commons Ontology Library 1.1 standard? I would be happy to walk through that with you :).

_Originally posted by @ElisaKendall in https://github.com/edmcouncil/fibo/issues/1816#issuecomment-2037906067_

**Comment by VladimirAlexiev** [comment]
hi @ElisaKendall, I would be very glad to do it!

I think the most efficient way is if you submit a PR against https://github.com/VladimirAlexiev/crunchbase-fibo: files
`prefixes.ttl ipos-agents.ttl ipos-offering.ttl ipos-financials.ttl ipos-currencies.ttl`.
Then I'll check (read about) all the changes and if warranted add a section describing the evolution.

Or do you prefer to do it in some other way?

**Comment by ElisaKendall** [comment]
@VladimirAlexiev I'll think about the journal, but will work on this in your crunchbase git repo. I'll likely need your assistance to test it though. I will send email once I've made some progress so that you can take a look :).

On places to publish, I'll also think about that. Possibly an EU conference since you are there.  Thanks!

**Comment by ElisaKendall** [comment]
@VladimirAlexiev I think I've made a first pass for you, but you need to give me permission to write to a separate branch in your crunchbase-fibo repo in order to push the changes out :)

**Comment by VladimirAlexiev** [comment]
@ElisaKendall can you fork my repo to `ElisaKendall/crunchbase-fibo`? After pushing there, Github will show you a link at your page that allows you to make a PR.

**Comment by ElisaKendall** [comment]
@VladimirAlexiev hmmm - I cloned it and created a branch. I was attempting to push my branch to the remote repo, not push anything into the main branch, but I don't have permission to do that. Would it be ok to simply push the branch or do I really need to fork it?

**Comment by VladimirAlexiev** [comment]
@ElisaKendall 
You need to fork it as `ElisaKendall/crunchbase-fibo`. ("Clone" just means that you get a local copy).

**Comment by ElisaKendall** [comment]
@VladimirAlexiev Ok - done. We use branches for our FIBO work, but only because there are a small number of contributors that work with a larger SME community.

**Comment by tahoeblue** [comment]
I am loosely following this thread without really understanding the purpose or details, but I am curious why a fork is needed in order  to support whatever additional definitions or specifications may be needed to satisfy the business requirements of Crunchbase (which is not a database technology but more a business content repository).

( Forks do create specifications and code bases that are separate and will ultimately diverge )

Just curious — I don’t really have a dog in this hunt :)

-Jeff

**Comment by VladimirAlexiev** [comment]
Thanks @ElisaKendall ! Normally you'd make a branch for each task/feature. But since here is only one task (to update), it's ok that you did it in your Master.
I left a couple of comments, please take a look. But I'll merge it now and will proceed to regenerate the figures and add a few more editorial things (which prefixes were changed).

@tahoeblue 
- I didn't fork FIBO to capture Crunchbase. I applied FIBO (and still use a custom CB ontology for minor things like "the URL of an IPO at the CB site). See  https://rawgit2.com/VladimirAlexiev/crunchbase-fibo/main/README.html. I'll be very grateful to get your comments!
- Elisa forked my repo so I can review her changes. That's the normal way to collaborate on Github.

**Comment by VladimirAlexiev** [comment]
- merged https://github.com/VladimirAlexiev/crunchbase-fibo/pull/1
- added section https://rawgit2.com/VladimirAlexiev/crunchbase-fibo/main/README.html#fibo-changes
- updated https://rawgit2.com/VladimirAlexiev/crunchbase-fibo/main/README.html#generating-semantic-transformation
- and of course updated Acknowledgements (thanks, @ElisaKendall ! I'd be happy to add you as co-author)
- committed https://github.com/VladimirAlexiev/crunchbase-fibo/blob/main/venues.md which is a list of potential publication venues (collected last year).
  - can also serve as a start of bibliography on FIBO
