### ISSUE TITLE
Eliminate / address obsolete restrictions identified through hygiene testing

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#2028]
There are a number of these that should be corrected.

**Comment by mereolog** [comment]
Among those, one is an obvious redundancy in the ontological description of DerivativeInstrument (which is in FIBO Prod), where

https://github.com/edmcouncil/fibo/blob/f2c598785946870a1dcc0d7217ab8c1690741afa/DER/DerivativesContracts/DerivativesBasics.rdf#L431-L434

can be derived from:


https://github.com/edmcouncil/fibo/blob/f2c598785946870a1dcc0d7217ab8c1690741afa/DER/DerivativesContracts/DerivativesBasics.rdf#L413-L416

Btw., note that such redundancies are indicated in onto-viewer:

![image](https://github.com/edmcouncil/fibo/assets/11171688/e469a3ae-979e-47a4-897d-9a307aba74f6)
