### ISSUE TITLE
Difference between location of EUSecuritiesRestrictions and its declaration in catalog-v001.xml

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#2032]
There is a difference between the actual location of https://github.com/edmcouncil/fibo/blob/master/SEC/Securities/EuropeanSecurities/EUSecuritiesRestrictions.rdf (1) and its declaration in the catalog-v001.xml file (2)
1. ./SEC/Securities/EuropeanSecurities/EUSecuritiesRestrictions.rdf
2. ./SEC/Securities/EuropeanJurisdiction/EUSecuritiesRestrictions.rdf
https://github.com/edmcouncil/fibo/blob/f344069437e724ee668fbf3d5667f4148101f5d3/catalog-v001.xml#L291

I think that the catalog file needs to be updated.

**Comment by ElisaKendall** [comment]
@mereolog This issue was corrected as part of the process of revising various metadata files related to SEC-199, pull request #2043
