### ISSUE TITLE
FIBO Products Download

### ISSUE THREAD

**Issue by peio** [edmcouncil/fibo#2058]
Dear FIBO team, 
 I am trying to get an updated version of FIBO. Usually, I use the [FIBO Products Page](https://edmconnect.edmcouncil.org/okgspecialinterestgroup/resources-sig-link/resources-sig-link-fibo-products-download), but presently the links lead me to the FIBO viewer.

Is this the intended behaviour?

Thank you

**Comment by przemekgradzki** [comment]
Dear @peio,
Of course, this wasn't intended behavior. The error was a side effect of introducing new functionalities on the server.

**Fixed**

In case of any problems, please do not hesitate to contact us

Many thanks
