### ISSUE TITLE
fibo-fnd-utl-alx:actualExpression misidentified with cmns-qtu:describesActualExpression

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#2069]
fibo-fnd-utl-alx:actualExpression is claimed to be equivalent to cmns-qtu:describesActualExpression, but the former is an annotation property and the latter is a datatype property - see below:

https://github.com/edmcouncil/fibo/blob/34c0e645285b70cece1c7a918ab0d6611c1f80ab/FND/Utilities/Analytics.rdf#L569-L572

[describesActualExpression](https://github.com/edmcouncil/idmp/blob/fe0d1236f26d29414fc7d1abeb7b5e3a13362ec9/CMNS/QuantitiesAndUnits.rdf#L826-L831)

**Comment by ElisaKendall** [comment]
@mereolog I think this is a bug in Commons - describesActualExpression is a subproperty of hasDescription which is an annotation property. Pete thought it should be a data property, but I believe we use it in every case as an annotation. I'll raise an issue against Commons. We can leave this for now as an open issue in FIBO, but mainly to document that this change in Commons needs to be made.

**Comment by ElisaKendall** [comment]
Close to the resolution included in pull request #2071
