### ISSUE TITLE
hasAddressLineN properties

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#237]
`fibo-fbc-fct-breg:` has properties `hasAddressLine1..4` and cites definitionOrigin http://www.leiroc.org/publications/gls/lou_20140620.pdf.

But do we need this seemingly random restriction to 4 address lines? We can have newlines in RDF literals, and thus accommodate any number of lines required.

Eg Dun & Bradstreet data has `StreetAddressLine1..4` in one case, but `MailingLabelLine1..8` in another case. how do you squeeze 8 DnB lines into 4 LEI/FIBO lines?

**Comment by rivettp** [comment]
FWIW FIBO and the GLEIF ontology do have distinct properties for city, country, postalcode, region. The addressLines are used for the remainder, which could be street address, building, floor, apartment, PO Box, "c/o person ", suite etc. Which is broader than "street address" and can be very country-dependent.

**Comment by VladimirAlexiev** [comment]
W3C LOCN has the most specific address fields. You can see them at https://github.com/euBusinessGraph/eubg-data/blob/master/model/ebg-shapes.shex or https://github.com/euBusinessGraph/eubg-data/blob/master/model/images/company.png.
