### ISSUE TITLE
Clarify definition of LegalPerson

### ISSUE THREAD

**Issue by qwaziers** [edmcouncil/fibo#274]
Discussion on our side has raised question around the "LegalPerson" definition:

- mentioning "entity" in the definition raised SME's question on whether an entity in this context was having the meaning of "legal entity" or of something else... Suggestion : change "entity" by "autonomous agent"
- does the definition implies as well that the legal person can also sue ? We supposed that yes and thus would like to make it explicit.

Here is our proposition : 

> any autonomous agent which can incur legal obligation and can sue and be sued at law

what do you think ?

**Comment by rivettp** [comment]
This is still a legitimate question/clarification and I would support the proposed clarification.

**Comment by ElisaKendall** [comment]
LegalPerson is defined in Business Entities (BE) - if we are planning to rephrase the definition then I propose that we modify it further to use American English, per our stated policy and per OMG policies, for example, 

autonomous agent that is recognized as having rights and obligations under the law, including but not limited to the right to sue and be sued, enter into contracts, own property, and incur financial and other obligations

**Comment by rivettp** [comment]
Suggestion seems good to me, @ElisaKendall 
BTW here is a link to the element https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LegalPersons/LegalPerson

**Comment by trypuz** [comment]
> autonomous agent that is recognized as having rights and obligations under the law, including but not limited to the right to sue and be sued, enter into contracts, own property, and incur financial and other obligations

This definition is OK. @ElisaKendall, do you want me to create PR, or do you want to?

**Comment by trypuz** [comment]
Check the PR #829 to examine the changes.
