### ISSUE TITLE
A Geopolitical entity is not a physical location

### ISSUE THREAD

**Issue by CoryCasanave** [edmcouncil/fibo#299]
The class "FND/Places/Countries/GeopoliticalEntity conflates the political organization with the geography it manages. This causes unacceptable inferences. Suggest as follows:
Geopolitical region is a role of a physical location. A Geopolitical entity (a kind of organization) governs such a region.

**Comment by rivettp** [comment]
There is

**Comment by ElisaKendall** [comment]
We are currently using the LCC ontologies for Location, GeographicRegion, and GeopoliticalEntity -- so this issue should be raised against the LCC ontologies in OMG, not against FIBO.

I'm closing this with no change since the ontology it applies to is outside of FIBO.
