### ISSUE TITLE
FIBO unsolvable resources

### ISSUE THREAD

**Issue by zoetsekas** [edmcouncil/fibo#418]
There are some resource links such as:
in fibo/fnd/Agreements/Agreements.rdf
<owl:versionIRI rdf:resource="https://spec.edmcouncil.org/fibo/FND/20160201/Agreements/Agreements/"/>

that cause OWL reasoners to throw an exception, as the resource cannot be found.

A lot of test data in the etc folder have the old resource path "http://www.omg.org/spec/EDMC-FIBO/FND/"

Could they be either deleted or renamed accordingly

**Comment by rivettp** [comment]
There are no longer any such references.
