### ISSUE TITLE
Need specifics on how volatility is measured; types of volatility

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#44]
To the added method concept defined in another issue, define sub class for the method used to determine Volatility, with appropriate methods or features.

**Comment by ElisaKendall** [comment]
This was completed under IND-30, IND-31, and IND-32 (JIRA issues), with one remaining open issue around the definition of FX Spot Volatility, for which we have an open JIRA issue, IND-33.

I recommend that we re-close this issue.
