### ISSUE TITLE
Fx: Revise the Numerator, Denominator currency labels

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#45]
Add new terms for Dealt versus Term, being the currencies of the exchange itself.

From Investopedia:
Base Currency; Quote or Counter Currency where Base is the one there is 1 of.

**Comment by ElisaKendall** [comment]
The current definition of ExchangeRate uses two properties: hasBaseCurrency and hasDealtCurrency - this was addressed years ago, replacing the numerator and denominator labels.  This issue is moot and should be closed.
