### ISSUE TITLE
Fx: Incomplete definition for Spot Rate

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#47]
Spot rates are quoted. Those quoted rates, as market data, are what’s referenced here. That should be reflected in the definition, which implies a specific rate for a (potential) trade. It is not the same as a rate in an actual Fx deal, since it is a quoted market rate.

Definition is currently as follows: 
The exchange rate at a point in time, with settlement at that same point in time. 
See also Bank of England definition: 
"The data represent indicative middle market (mean of spot buying and selling) rates as observed by the Bank's Foreign Exchange Desk in the London interbank market around 4pm. A monthly working day average is published. They are not 'official' rates and are no more authoritative than rates provided by any commercial bank operating in the London market. Spot rates are applicable to deals executed for settlement two working days later."

**Comment by ElisaKendall** [comment]
This issue was addressed ages ago.  The current hierarchy for exchange rates is:
ExchangeRate
     QuotedExchangeRate
          CurrencyForwardRate
          CurrencySpotRate
               CurrencySpotBidRate
               CurrencySpotMidRate
               CurrencySpotSellRate

I don't recall when these changes were made or with what issue number, but the issue was addressed years ago given the current structure.  I recommend we re-close this issue as moot.
