### ISSUE TITLE
Fx: Add property to Spot rate identifying the time to settlement for which the spot rate is quoted

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#48]
See BoE definition for Spot rate. Settlement is a market convention and “2” is an example of such a convention for the London market. 
See also Bank of England definition: 
"The data represent indicative middle market (mean of spot buying and selling) rates as observed by the Bank's Foreign Exchange Desk in the London interbank market around 4pm. A monthly working day average is published. They are not 'official' rates and are no more authoritative than rates provided by any commercial bank operating in the London market. Spot rates are applicable to deals executed for settlement two working days later."

**Comment by ElisaKendall** [comment]
We have added this to currency forward rate - a settlement date may apply to a contract that is based on foreign exchange rates but not to the quoted spot rate as of a particular date and time.  So this no longer applies to the current ontology, which is significantly different from the ontology as it was in 2014.
