### ISSUE TITLE
Fx: Fx Rates add block amount property

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#49]
Include property in Fx Spot / all Fx Rates for the block amount against which a quoted Fx rate is quoted.
This should possibly be a feature of the “Method”.

**Comment by ElisaKendall** [comment]
Currency rates are negotiated on a transaction basis - and the rate applies to the total amount.  Rates are not dependent on the nominal amount of the transaction.  The rate is the rate, and based on our current ontology, this is a non-issue according to several bankers I've asked.
