### ISSUE TITLE
Fx: Fx Forward rates should be quoted as premium against a spot rate

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#51]
Remove inheritance link from Fx Forward to Fx Rate. Review whether Fx Rate would still exist as an abstract of anything other than Fx Spot. Add object property to Fx Forward identifying the rate against which it is quoted. Revise the datatype for Fx forward to reflect that it is a premium not a rate.

**Comment by rivettp** [comment]
@MikeHypercube I'm a bit confused since fxForwardRate is a property. Please review whether there is still a problem.

**Comment by ElisaKendall** [comment]
The Foreign Exchange concepts related to this issue have been completely refactored over the last 5 years.  The hierarchy has been redesigned - there is no longer an Fx Forward datatype ... Not sure what reopening this issue is intended to do.
