### ISSUE TITLE
IR: Rename various Classes

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#56]
• Rename InterestReferenceRate to ReferenceRate
• Rename OvernightInterestRate to OvernightRate
• Rename USFedFundsRate to FedFundsRate
• Rename BaseRate to BankBaseRate

**Comment by rivettp** [comment]
BaseRate at least has not been renamed.

**Comment by ElisaKendall** [comment]
The renaming was done years ago by the IND FCT.  This issue should remain closed as the work was completed.  Most of the names identified above are those in the current ontology, although we renamed InterestReferenceRate to ReferenceInterestRate, and USFedFundsRate to FederalFundsRate, per the US Treasury Department convention.

This issue should be closed given that the work has already been done.
