### ISSUE TITLE
EI: UnemploymentRate temporality question. 

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#61]
Unclear why UnemploymentRate applies to a period and not a point in time. 

Proposed change: This is something which sounds like it might be asserted at a point in time, though different periods might be relevant to the "Method" in some way. Review and revise.

**Comment by ElisaKendall** [comment]
The current definition of UnemploymentRate is far more sophisticated, per the work that the IND FCT has done with the assistance of BLS.  It includes the date on which the rate is published as a release date, but the rate itself is for a reference period.  This issue has been made moot by the work of the IND FCT and should remain closed.
