### ISSUE TITLE
Circular definition for hasOperand

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#69]
This is in the Analytics ontology now.

Definition for “hasOperand” is circular and cannot find one for “operand”.

**Comment by trypuz** [comment]
See: [https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/hasOperand](https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/hasOperand) in FIBO Viewer.

**Comment by ElisaKendall** [comment]
This property, hasOperand, was likely intended to be hasOperator, and is not used anywhere in FIBO.  I suggest that we simply remove it.

**Comment by trypuz** [comment]
@ElisaKendall , if you haven't changed your mind about this property, could you remove it, please.

**Comment by ElisaKendall** [comment]
@trypuz - ok - I'll take care of it soon.
