### ISSUE TITLE
FIBOModule and FIBODomain (subclasses of sm:Module)

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#756]
@ElisaKendall - Currently, under http://www.omg.org/techprocess/ab/SpecificationMetadata/Module we have a flat list of FIBO domains and modules. I'd like to suggest we have two subclasses of http://www.omg.org/techprocess/ab/SpecificationMetadata/Module, namely: FIBOModule and FIBODomain. Are there any contraindications?

**Comment by ElisaKendall** [comment]
I think that makes sense @trypuz - the viewer should display the contents of the metadata for that domain/module, and at the FND domain level, that information is contained in the MetadataFND/FNDDomain element.
