### ISSUE TITLE
Add Government and Quasi-government entities

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#78]
The so-far needed government-related entity types should be in a new module in the FIBO-BE FunctionalEntities module. 

These were flagged as future scope in FIBO and have explicitly never been completed, but many of these terms do exist in the EA model. We introduced some of them to IND as they were needed. Those which are needed now are to go in the new module, and as we add more of these (e.g. for debt issue) they would extend that ontology. 
Scope to include NGOs and international bodies.

**Comment by rivettp** [comment]
We do now have NGO
