### ISSUE TITLE
The AboutFIBOProd and AboutFIBODev ontologies have bogus IRIs and need to be documented with metadata that can help github users

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#814]
These files have only been used by "insiders" while working with the ontologies in github to date, but with an open repository they will become essential to developers. They need to be documented, including relevant header details, just as any other ontology in FIBO and managed appropriately. They also need to be kept up to date as part of our process.

These files work with the github versions of the ontologies, rather than the published versions, whose IRIs are distinct from these. They were automatically published at some point but have been corrupted over time. The process that used to generate them should either be repaired or abandoned.

**Comment by ElisaKendall** [comment]
This issue corresponds to FND-273 in JIRA.

**Comment by trypuz** [comment]
@dallemang , @ElisaKendall , what exactly should be done to fix this issue?

**Comment by ElisaKendall** [comment]
@trypuz - I've put this on hold until I finish merging some of the loans ontologies, because they need to be fixed manually.  There should be a nice header and information about each of the versions, like with the all files I've been maintaining under each domain area, but I don't want to do this until after I've eliminated / merged more ontologies.
