### ISSUE TITLE
FIBO Viewer for FIBO Development and FIBO Production

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#824]
It was suggested by @jgeluk and @dallemang that FIBO Viewer should allow selection of the FIBO version to browse, i.e., to choose between FIBO Development and FIBO Production. @dasawanaka can we have two instances of FIBO Viewer API, one for FIBO Development and the second one for FIBO Prod?

**Comment by dasawanaka** [comment]
The module tree (displayed on left hand side) does not exist in FIBO prod version. I think we can inform which FIBO resources come from the released ontologies.

**Comment by trypuz** [comment]
We will use colors to indicate dev and prod; each ontology will be green or yellow; modules and domains will inherit colors from the ontologies they group.
![image](https://user-images.githubusercontent.com/6771512/73957271-6d439b00-4906-11ea-893b-070de341f5a6.png)
