### ISSUE TITLE
Merge concepts from Documentation in InformationExt with the existing Documents ontology and eliminate the informative ontology

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#827]
There are a number of redundant/unneeded concepts in this ontology, which should be eliminated.

**Comment by trypuz** [comment]
@ElisaKendall, could we have a list of the redundant/unneeded concepts, please?

**Comment by ElisaKendall** [comment]
The informative ontology includes many redundant concepts, such as Document, InsurancePolicy, Prospectus, and Report, and includes many unnecessary concepts such as WrittenInformation, WrittenCommunication, ControlDocument, Declaration, DocumentInformation, DocumentStatus, various kinds of draft documents, draft document parts, forms, and so forth.  Most of these elements are poorly defined, as is the case for most informative ontologies.  

The concepts that are included in this ontology that are not redundant, such as Certificate, Notice, and TermSheet, should be moved as appropriate to either the Documents or Contracts ontology and the informative ontology should be eliminated.
