### ISSUE TITLE
Eliminate the largely redundant InfoCore, Messaging, and TemporalInfo ontologies

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#840]
These ontologies duplicate content in existing released ontologies and add little value.  Any concept that is needed in a provisional ontology that is not a duplicate should be moved to where it is used, and the rest should be removed altogether.  New users could be confused by them and thus the technical debt we have from keeping them is not worth the cost.

Examples include: 
- [fibo-fnd-inf-tem;AnalyticsCalculationModel](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/TemporalInfo/AnalyticsCalculationModel), which is redundant with [fibo-fnd-utl-alx;Formula](https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/Formula), 
- [fibo-fnd-inf-tem;Phase ](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/TemporalInfo/Phase) and [fibo-fnd-inf-tem;Status](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/TemporalInfo/Status) which are redundant with [fibo-fnd-arr-lif;LifecycleStage](https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Lifecycles/LifecycleStage)
- [fibo-fnd-inf-inf;Information](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/InfoCore/Information) and [fibo-fnd-inf-inf;WrittenInformation](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/InfoCore/WrittenInformation) which are redundant with [fibo-fnd-arr-doc;Document](https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Documents/Document),
- [fibo-fnd-inf-msg;ApplicationInformation](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/Messaging/ApplicationInformation) and [fibo-fnd-inf-msg;Request](https://spec.edmcouncil.org/fibo/ontology/FND/InformationExt/Messaging/Request) which are redundant with the concepts in the provisional [Communications ontology](https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Communications/), also in [FND/Arrangements](https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/MetadataFNDArrangements/ArrangementsModule)

**Comment by trypuz** [comment]
@ElisaKendall, what you mean by "Communications ontology"?

We should also consider that we have in FIBO:
- [3 resources labeled "status"](https://spec.edmcouncil.org/fibo/ontology?searchBoxQuery=status)
- [2 resources labeled "information"](https://spec.edmcouncil.org/fibo/ontology?searchBoxQuery=Information)
- [2 resources labeled "document"](https://spec.edmcouncil.org/fibo/ontology?searchBoxQuery=Document)
- [2 resources labeled "request"](https://spec.edmcouncil.org/fibo/ontology?searchBoxQuery=Request)

**Comment by rivettp** [comment]
@trypuz the Communications ontology is https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Communications/
