### ISSUE TITLE
Eliminate the redundant 'Tools and Instruments' and 'Methods and Rules' informative ontologies

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#843]
These two ontologies include very few terms that are referenced anywhere else in FIBO, and those few terms are redundant with concepts in existing ontologies.

Examples include:
- [fibo-fnd-arrxx-ins;FinancialInstrument](https://spec.edmcouncil.org/fibo/ontology/FND/ArrangementsExt/ToolsAndInstruments/FinancialInstrument), which is redundant with [fibo-fbc-fi-fi;FinancialInstrument](https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/FinancialInstrument)
- [fibo-fnd-arrxx-ins;Purpose](https://spec.edmcouncil.org/fibo/ontology/FND/ArrangementsExt/ToolsAndInstruments/Purpose), which, in it's current usage, is redundant with [fibo-fnd-gao-obj;Objective](https://spec.edmcouncil.org/fibo/ontology/FND/GoalsAndObjectives/Objectives/Objective)
-[ fibo-fnd-arrxx-meth;Method](https://spec.edmcouncil.org/fibo/ontology/FND/ArrangementsExt/MethodsAndRules/Method), which in it's current usage is redundant with [fibo-fnd-gao-obj;Strategy](https://spec.edmcouncil.org/fibo/ontology/FND/GoalsAndObjectives/Objectives/Strategy)

The redundant concepts, especially FinancialInstrument, really need to be eliminated.

**Comment by trypuz** [comment]
BTW, [hasInvestmentStrategy](https://spec.edmcouncil.org/fibo/ontology/CIV/Funds/CIV/hasInvestmentStrategy) has label "strategy"; it should be changed.
