### ISSUE TITLE
OWL API and the ontology annotations problem

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#846]
This issue concerns the problem that some of the FIBO users may experience if they use OWL API to process FIBO. FIBO Viewer is a victim of this problem too. Namely, the problem is that the ontology annotations are not read by OWL API if (in the file) they go after imports. It seems that OWL API reads FIBO files line by line (triple by triple). @dasawanaka reported this error here: [https://github.com/owlcs/owlapi/issues/903](https://github.com/owlcs/owlapi/issues/903). We learned that it is the same bug as [https://github.com/owlcs/owlapi/issues/895](https://github.com/owlcs/owlapi/issues/895) and "that it has been fixed last November but there has been no release with the fix yet". We are waiting to learn when the new OWL API release including the fix will be. Maybe we should consider putting ontology annotations before imports?

**Comment by rivettp** [comment]
Resequencing our ontologies would be hugely disruptive and rewire a Serializer change and result in unnecessary diffs in all ontologies. For what is a transient and fixed November regression in OWL API. If there is no release pending we could revert to the earlier release or build it ourselves.

**Comment by trypuz** [comment]
Good news: https://github.com/owlcs/owlapi/issues/903#issuecomment-578707794

**Comment by trypuz** [comment]
OWLAPI 5.1.3 released. https://github.com/owlcs/owlapi/issues/903#issuecomment-579467952
