### ISSUE TITLE
Broken links in 'How to contribute' document

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/fibo#856]
The two links in the '[Bug reports and feature requests](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#bug-reports-and-feature-requests)' section of '[How to contribute](https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md)' document are broken, i.e., they produce the 404 error:

1. [Bug report](https://github.com/edmcouncil/fibo/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
2. [Feature request](https://github.com/edmcouncil/fibo/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)

**Comment by rivettp** [comment]
Also this one, which seems a lot more important https://github.com/edmcouncil/fibo-infra/tree/master/jenkins/bin/dev_toolkit.zip
