### ISSUE TITLE
Range of isDomiciledIn should not be Country

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#859]
(Also https://jira.edmcouncil.org/browse/FND-279)

The property is https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/FormalOrganizations/isDomiciledIn
See discussion here https://www.upcounsel.com/corporate-domicile which makes clear that domicile is (in addition to incorporation) at the State level in the US.

BTW the definition "the country in which the formal organization is officially domiciled" makes use of "domicile" which is somewhat circular but should be based on the common use of the term as per the link.  
If we really want a property for the country we should have a new property e.g. hasCountryOfDomicile.

**Comment by ElisaKendall** [comment]
Closed to pull request #881 / FND-279
