### ISSUE TITLE
Labels on a few of the individuals in FBC are not unique

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#887]
The labels on some of our US regulatory and US financial services entities are not unique and should be corrected.

Also, the LEI records for some of these individuals may be out of date and should be updated.

**Comment by ElisaKendall** [comment]
This issue is related to, but much smaller than, #875, and corresponds to FBC-239 in JIRA.

**Comment by rivettp** [comment]
I can only see 2 (at the top of the list in #875) - for a couple of addresses.

I don't think we should spend valuable time keeping examples up top speed with ongoing LEI record changes in GLEIF (e.g. when the date when someone renews their registration). These are just examples not reference data! So long as we make that clear that's all we should do.

**Comment by ElisaKendall** [comment]
So, I had to update those to fix the date time stamp issue, and added S&P Global LEI in this fix.
