### ISSUE TITLE
A couple of random catalog files in GitHub for no reason

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#891]
We seem to have a couple of catalog files at random in GitHub, which has always baffled me:
  catalog-v0001.xml (at root)
  FBC/FunctionalEntities/catalog-v0001.xml

**Comment by ElisaKendall** [comment]
The top-level one in FIBO needs to be there for ease of use.  Many FIBO users are not going to manually generate a catalog.  The one at the top level should be generated every time changes are made.  The one in FBC can go away, but the top level catalog should be available for users, and should be relative.

**Comment by ElisaKendall** [comment]
I'm concerned about ease of use - and actually want catalogs for each domain (and maintain those myself at the moment) to allow people to work effectively at any domain level.  The various All files help with that but you need a catalog file to go with those for each domain.

**Comment by rivettp** [comment]
@ElisaKendall when you say "The one at the top level should be generated every time changes are made." does that mean someone manually needs to do this? I would not support that, but if so it needs to be in the contributing guide. 
And users of the tool need to be told about them here https://spec.edmcouncil.org/fibo/ontology-tools - otherwise they're of benefit only to you!

More generally I'm somewhat uncomfortable including in our source GitHub files that are proprietary and relevant only to one specific tool: they should at least be documented/segregated as such. 
For my purposes they are clutter and do get in the way - I have to specifically remove them when processing FIBO directories.
Another question is whether they (should) appear in both source and published files.

**Comment by rivettp** [comment]
BTW there no longer seems to be a catalog file in FunctionalEntities
