### ISSUE TITLE
Eliminate duplicate collection and arrangement classes in FND in favor of those defined in LCC

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#897]
There are a number of duplicate classes in FND, such as arrangement and collection, that are defined in LCC. The FIBO duplicates should be eliminated to simplify the hierarchy for FIBO users.  If there are additional semantics in FIBO, then those details should be retained, but anything that is a 1-1 duplicate should be eliminated in favor of the LCC class or property.

**Comment by rivettp** [comment]
Why not also eliminate the use of fnd-rel-rel:hasTag in favor of lcc-lr:hasTag?

**Comment by ElisaKendall** [comment]
This was completed for the Q3 release in 9/2020 and should be closed.
