### ISSUE TITLE
IR: Add New subclasses for FedFundsRate

### ISSUE THREAD

**Issue by MikeHypercube** [edmcouncil/fibo#91]
we should create subclasses for FedFundsRateEffective
      and FedFundsRateTarget

**Comment by rivettp** [comment]
We still don't have these, so re-opening: I think this was an administrative closure.

**Comment by ElisaKendall** [comment]
The Fed publishes a single daily rate: "As of March 1, 2016, the daily effective federal funds rate (EFFR) is a volume-weighted median of transaction-level data collected from depository institutions in the Report of Selected Money Market Rates (FR 2420). Prior to March 1, 2016, the EFFR was a volume-weighted mean of rates on brokered trades."  And, they don't break that down beyond a single rate on their web site - see https://www.federalreserve.gov/releases/h15/.

Also: "The effective federal funds rate is the interest rate banks charge each other for overnight loans to meet their reserve requirements. Also known as the federal funds rate, the effective federal funds rate is set by the Federal Open Market Committee, or FOMC.", see www.bankrate.com/glossary/e/effective-federal-funds-rate/.  

And: "Federal Funds Rate Definition. The federal funds rate definition, or fed funds rate, is the target interest rate for overnight lending and borrowing transactions between banks. The Federals Open-Market Committee ( FOMC ) sets the US fed funds rate. FOMC is a committee within the central bank of the United States. (For current and historic fed funds rates see the links below).", see strategiccfo.com/federal-funds-rate-definition/.

The terms are synonyms, in other words. This is a non-issue.
