### ISSUE TITLE
RelationshipRecord should not subclass Record

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#915]
Since a whole registry is one Record, it's inconsistent that a single [&fibo-be-le-lei;RelationshipRecord](https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LEIEntities/RelationshipRecord) within such a registry is also one Record.
I'm not sure either level really meets the definition of Record as "a memorialization and objective evidence of activities performed, events occurred, results achieved, or statements made..."

_Originally posted by @rivettp in https://github.com/edmcouncil/fibo/pull/913/files_

**Comment by trypuz** [comment]
Solved by #913. https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/LEIEntities/RelationshipRecord
