### ISSUE TITLE
Unexpected triple in 'qualified measure'

### ISSUE THREAD

**Issue by ubbc** [edmcouncil/fibo#933]
[https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/QualifiedMeasure](https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/QualifiedMeasure)

is restricted as `is calculated via methodology min 0 anyURI or string`

This is expressed through the triples

```
fibo-fnd-utl-alx:QualifiedMeasure
	a owl:Class ;
	rdfs:subClassOf
		[
			a owl:Restriction ;
			owl:onProperty fibo-fnd-utl-alx:isCalculatedViaMethodology ;
			owl:minQualifiedCardinality "0"^^xsd:nonNegativeInteger ;
			owl:onDataRange [
				a owl:Class ;
				owl:unionOf (
					xsd:string
					xsd:anyURI
				) ;
			] ;
		]
		;
```
The data range (xsd:string or xsd:anyURI)  should not be  `a owl:Class`, it should be `a rdfs:Datatype`.

**Comment by VladimirAlexiev** [comment]
@ubbc you are right but anyURI is a string, 
so @ElisaKendall and @trypuz I sort of fail to see the purpose of this union.

I wouldn't nitpick but I am not aware of any repo to implement datatype unions. Do you know some?

**Comment by ElisaKendall** [comment]
Stardog supports this, not sure about other repositories.
