### ISSUE TITLE
Correct orphaned property references left over from LCC changes

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#940]
The following orphans were uncovered during further testing:

1. In EuropeanFinancialServicesEntitiesIndividuals, there is an orphan fibo-fnd-rel-rel:isMemberOf that should be lcc-lr:isMemberOf
2. In USRegulatoryAgencies there are a number of fibo-fnd-rel-rel:hasMember that should be lcc-lr:hasMember

**Comment by rivettp** [comment]
@dallemang how come these were not picked up by hygiene tests? Do we need a new issues for thato
