### ISSUE TITLE
Hygiene tests are to be revisited

### ISSUE THREAD

**Issue by trypuz** [edmcouncil/fibo#943]
Some recent issues (e.g. #940) have shown that our hygiene tests need to be revised.  We need to document the existing ones and list the missing ones.

**Comment by ElisaKendall** [comment]
One of the issues that keeps coming up is that our hygiene tests do not include individuals.  While there is some debate about whether or not individuals need both labels and definitions, we should at least be checking to make sure every URI references something that exists somewhere (i.e., catch misspelled prefixes) and there should not be any 'funny' characters that are not allowed in RDF/XML to be present in any definitions, labels, etc., and every individual should be typed.

**Comment by ElisaKendall** [comment]
Note that at least some of the existing and many desired hygiene tests are listed in the ontology guide.
