### ISSUE TITLE
An additional datatype property is needed for local designations for states and provinces

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#947]
Currently the US postal addressing standard uses the LCC regions, and adds annotation properties for preferred designation. For data mapping purposes, we need datatype properties in addition to the annotations that provide the same text value, for US and Canadian states and provinces. Other postal addressing locals may need something similar, so this property, hasLocaleDesignation, should be in the main address ontology, with its use for the US and Canada in the US-specific individuals ontology.

**Comment by rivettp** [comment]
I'm not convinced...
a) Why not use one of the existing annotation properties such as skos:altName or fibo-utl-av:abbreviation? You're normally into property reuse!
b) In either case these should be properties of the LCC CountrySubdivision not of the Address

**Comment by ElisaKendall** [comment]
This is intended to be a property of the code for the country subdivision, perhaps I wasn't clear.  The problem with reusing any of these properties is that they are annotations.  What we need for mapping purposes is a datatype property.  We are already using preferredDesignation, which is an annotation property itself and a subproperty of skos:altLabel.  But annotations are not sufficient for our purposes with respect to mapping to multiple databases.  The mapping needs to resolve to a data value, not an annotation in our applications.  This is a very common pattern that we want to support, in fact, one that many banks will need.  At least two that I am aware of.  SPARQL, the OWL API, and other tools do not recognize / facilitate the use of annotations in the same way that they support datatypes.   Both are important for different reasons.
