### ISSUE TITLE
Update Developers Guide

### ISSUE THREAD

**Issue by dallemang** [edmcouncil/fibo#955]
There are many issues in the developers guide, that nee to be managed.  Many of these are outlined in the discussion as part of https://github.com/edmcouncil/fibo/pull/888

That PR is about broken links, and not about all the issues that need to be fixed in the developers' guide.  I will try to sort those issues out as part of this issue, but I want to approve the broken links in the meantime.

**Comment by dallemang** [comment]
I want to start by bringing over my synopsis comment from #888 

A short synopsis of the history that led to many of these issues is that I created a number of scripts and a workflow that was to be followed by FIBO developers. But getting those scripts to run in various environments turned out to be much more complicated than just including them in the git repo (which is what I planned). As @MikeHypercube pointed out, there are some operational things that some of us take for granted that are challenging for people who use their computers differently.

**Comment by rivettp** [comment]
See also a bunch of things in #862

**Comment by mereolog** [comment]
Closed to the lack of activity.
