### ISSUE TITLE
fibo-fbc-fct-ra:hasIdentity missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#956]
https://spec.edmcouncil.org/fibo/ontology/master/latest/dev.fibo-quickstart.ttl
fibo-fbc-fct-ra:hasIdentity is used on fibo-fbc-fct-usjrga:CaliforniaBusinessRegistrar but not defined

**Comment by ElisaKendall** [comment]
Thank you for catching this - our hygiene tests ignore individuals, and I totally missed this.  I'll fix it ASAP.

**Comment by ElisaKendall** [comment]
Vladimir - I just fixed it at the pull request linked above - please take a look and if you are happy with the correction, approve the pull request.

**Comment by ElisaKendall** [comment]
This was fixed yesterday via pull request #958
