### ISSUE TITLE
How do I import the entire FIBO ontology?

### ISSUE THREAD

**Issue by Radu3000** [edmcouncil/fibo#966]
Right now it is broken into parts ... 

Is it possible to import the entire ontology?

If so what file?

**Comment by ElisaKendall** [comment]
There are two options in the github version of FIBO (i.e., not the quarterly publication, but the latest versions in github).  
1.  If you want to load all of the RELEASED ontologies in Protege for review, there is a load file and relative catalog for that.  The load file is in github at the top level under 'fibo', called AboutFIBOProd.rdf.  You can open that one in Protege at that location and the catalog is in that folder and should allow everything to load.  
2.  If you want -everything-, including content that has not been vetted and that may not be logically consistent, (i.e., the development version), you can open AboutFIBODev.rdf in the same folder, and you'll get everything.
3.  If you have downloaded the quarterly release, there are corresponding load files I think, at the top level in the zip archive(s). 
4. If you want to load them all from a URL, using follow your nose, there are files available for Production and Development, similar to the about files in the git archive, that you can use for that purpose.

Let me know if that does it for you or if you have more questions,

Elisa

**Comment by mereolog** [comment]
Adding to what @ElisaKendall said, you can also get the whole ontology using "quick" files"

1. for production release: https://spec.edmcouncil.org/fibo/ontology/master/2020Q1/prod.fibo-quickstart.ttl
2. for development release: https://spec.edmcouncil.org/fibo/ontology/master/latest/dev.fibo-quickstart.ttl

**Comment by jziemer2** [comment]
I downloaded https://spec.edmcouncil.org/fibo/ontology/master/2020Q1/prod.ttl.zip and extracted the compressed folder.
In Topbraid Composer, I just had to open LoadFIBOProd.ttl, it imports all other ontology files.
5 minutes, no issues - great work, FIBO team.

**Comment by Radu3000** [comment]
Elisa, Pete, and Jurgen,

Thank you for all your answers.  

Regards,
Radu

**Comment by rivettp** [comment]
I assume these responses addressed your question, @Radu3000, so am closing the issue.
