### ISSUE TITLE
Extra blank skos:definition on fibo-fnd-plc-adr:PhysicalAddressIdentifier

### ISSUE THREAD

**Issue by jziemer2** [edmcouncil/fibo#970]
This leads to a duplicate record in a SPARQL query for FIBO classes.
Release: https://spec.edmcouncil.org/fibo/ontology/master/2019Q1/prod.ttl.zip
Fix: delete the blank annotation property

```
fibo-fnd-plc-adr:PhysicalAddressIdentifier
  rdf:type owl:Class ;
  rdfs:comment "QName: fibo-fnd-plc-adr:PhysicalAddressIdentifier" ;
  rdfs:isDefinedBy fibo-fnd-plc-adr: ;
  rdfs:label "physical address identifier" ;
  rdfs:subClassOf owl:Thing ;
  rdfs:subClassOf lcc-lr:CodeElement ;
  rdfs:subClassOf lcc-lr:Identifier ;
  rdfs:subClassOf [
      rdf:type owl:Restriction ;
      owl:onClass fibo-fnd-plc-adr:PhysicalAddress ;
      owl:onProperty lcc-lr:identifies ;
      owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
    ] ;
  rdfs:subClassOf [
      rdf:type owl:Restriction ;
      owl:onClass fibo-fnd-plc-adr:PhysicalAddressingScheme ;
      owl:onProperty lcc-lr:isMemberOf ;
      owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
    ] ;
  skos:definition "" ;
  skos:definition "unique identifier for a physical address" ;
  skos:example "Physical address identifiers may include bar codes, QCR codes, and +codes in a number of countries." ;
```

**Comment by rivettp** [comment]
The problem is also in the original RDF/XML source:
		<rdfs:label>physical address identifier</rdfs:label>
		<skos:definition></skos:definition>
		<skos:definition>unique identifier for a physical address</skos:definition>

However, @jziemer2 , though it does not make sense here with a blank value, there is nothing IMO inherently wrong with having multiple triples for the same annotation property on a resource. So your SPARQL query processing should be able to cope.

**Comment by ElisaKendall** [comment]
I will have fixed this by the end of the day today, fyi, but I agree with Pete.  I'm wondering though, whether or not we should allow more than one skos:definition - other annotations yes, but multiple skos:definition in the same natural language maybe not?

**Comment by jziemer2** [comment]
@rivettp, as long as it is consistent.
One out of 1800 classes with more than skos: definition suggests a bug. There should be only one definition and label, but there can be several instances of the various SKOS notes. My query handles multiple annotation property instances, but it shouldn't concatenate two labels.
