### ISSUE TITLE
URI error in individuals (caught by Pellet Lint)

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#971]
In US Regulatory Agencies, there is an occurrence of fibo-fbc-fct-ra:hasIdentity, which should be fibo-fnd-rel-rel:hasIdentity - not caught by hygiene testing which ignores individuals

This is likely due to a copy / paste error that has been there for quite awhile, and our hygiene tests should be updated to catch these things.

**Comment by VladimirAlexiev** [comment]
I found this in #956 while playing with some counts:  rdfs:Property that are not OWL properties:

```sparql
select (count(*) as ?c) {
?x a rdf:Property 
filter not exists {?x a ?t. filter(?t in (owl:ObjectProperty, owl:DatatypeProperty, owl:AnnotationProperty))}
}
# 47
```
    - system props like: rdf:type rdf:subject rdfs:domain owl:onClass owl:hasValue
    - dct:hasPart: hmm, not found in quickstart?
    - fibo-fbc-fct-ra:hasIdentity as reported here
    - fibo-fnd-utl-av:scopeNote
