### ISSUE TITLE
FIBO Viewer direct vs "query" links

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#974]
Look at eg https://spec.edmcouncil.org/fibo/ontology/BE/LegalEntities/NorthAmericanEntities/USExampleEntities/TheCoca-ColaCompany-US-DE and https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals/TheCoca-ColaCompanyCorporateAddress. Most links are "direct" like this one, and exploring them shows the module/ontology hierarchy on the left.

But the following are "query" links. They still resolve, but fall out of the browsing hierarchy, and any of their **outgoing** links seem to degrade to "query" links:
- [United States of America (the)](https://spec.edmcouncil.org/fibo/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FLCC%2FCountries%2FISO3166-1-CountryCodes%2FUnitedStatesOfAmerica)
- UnitedStates
- Georgia
- Atlanta

**Comment by trypuz** [comment]
@VladimirAlexiev, thank you. Please notice that "United States of America (the)" has the following IRI: https://www.omg.org/spec/LCC/Countries/ISO3166-1-CountryCodes/UnitedStatesOfAmerica . In the FIBO Viewer, external to the spec URLs are handled by the query links. See e.g.  https://spec.edmcouncil.org/fibo/ontology?query=http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23subClassOf

**Comment by VladimirAlexiev** [comment]
OK, I understand the reason now. Then I'd argue to bring LCC into the fold and display it as an extra "module".
It's a pity that Atlanta is "in the fold" (my mistake above) while Georgia is not.

**Comment by trypuz** [comment]
The discussion has been moved to #981.
