### ISSUE TITLE
FIBO Viewer maturity icons need tooltip

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#975]
https://spec.edmcouncil.org/fibo/ontology shows green, yellow and green-yellow icons (dots). I assume these correspond to the levels of maturity "release, provisional, informative" as described at the same page.
Please add tooltips over the icons with the maturity level.

How do maturity levels relate to Production vs Development (and how do you even call this: development stage?) 
Please explain at the same page.

**Comment by VladimirAlexiev** [comment]
https://github.com/edmcouncil/fibo/blob/master/CONTRIBUTING.md#publication-maturity-levels calls "Production vs Development" -> "publication maturity levels". 

I find it a bit confusing to use the phrase "maturity levels" for two different set of things but I haven't yet read that section. Maybe some sort of matrix there can help understanding?

@trypuz how can I label issues myself?

**Comment by VladimirAlexiev** [comment]
Ok, it's explained clearly:
- Production is made up of the Release sources only.
- Development is made up of sources from Release, Provisional, and Informative levels

Maybe add a simple Venn to illustrate this.

**Comment by trypuz** [comment]
I'll take care of this issue.

**Comment by trypuz** [comment]
Fixed by https://github.com/edmcouncil/html-pages/pull/5.
