### ISSUE TITLE
Untyped data values (was "RSSD ID" wrong datatype)

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#979]
`fibo-fbc-fct-usjrga:ResearchStatisticsSupervisionDiscountIdentifier 
fibo-fnd-utl-av:abbreviation "RSSD ID"^^xsd:anyURI`

**Comment by rivettp** [comment]
Took me a little while to work out the problem - which is that this specific abbreviation string value should not have the anyURI datatype.

I then spotted another instance - happens to be in the same ontology:
	<owl:Class rdf:about="&fibo-fbc-fct-usjrga;IssuerIdentificationNumber">
...
		<fibo-fnd-utl-av:abbreviation rdf:datatype="&xsd;anyURI">IIN</fibo-fnd-utl-av:abbreviation>

**Comment by ElisaKendall** [comment]
Fixing both, with pull request coming shortly.

**Comment by VladimirAlexiev** [comment]
I found 14 instances with this query:

```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select * {
    ?x ?p ?y
    filter(datatype(?y)=xsd:anyURI)
    filter(!strstarts(str(?y),"http"))
}
```
They include the above two values, plus:
- "Note that Canada does not...": mere string
- "www.bcorporation.net": not proper URL
- "OptionsEducation.org": not proper URL

**Comment by VladimirAlexiev** [comment]
@trypuz Please reopen because of these strings improperly marked as anyURI:
- "Note that Canada does not...": mere string
- "www.bcorporation.net": not proper URL
- "OptionsEducation.org": not proper URL

**Comment by VladimirAlexiev** [comment]
@trypuz my last comment?

**Comment by ElisaKendall** [comment]
@trypuz I just checked - the datatype issue in CA Economic Indicators is still there with respect to the note Vladimir identified.  The reference to bcorporation.net is also still there, in BE in Corporate Bodies.  OptionsEducation.org is also still there, in ForeignExchange.  We haven't touched these ontologies in ages, which is likely why this is still open, but they need to be fixed and we should add a hygiene test for this.

**Comment by ElisaKendall** [comment]
@trypuz The two pull requests for the individual issues referenced above fix the ones mentioned by Vladimir, but once those are merged please check again before closing this, and also @mereolog please add a hygiene test for this.  Protege ignores it, and Pellet doesn't complain either, likely because these issues show up in annotations.

**Comment by trypuz** [comment]
Thanks, Elisa! Fixed.
