### ISSUE TITLE
clarify the use of synonym vs altLabel

### ISSUE THREAD

**Issue by VladimirAlexiev** [edmcouncil/fibo#980]
fibo-fnd-utl-av defines a number of subprops of `skos:altLabel`:
fibo-fnd-utl-av:abbreviation
fibo-fnd-utl-av:synonym
fibo-fnd-utl-av:commonDesignation
fibo-fnd-utl-av:preferredDesignation
fibo-fnd-utl-av:symbol

Of these `fibo-fnd-utl-av:synonym` is especially important: see https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-synonyms-as-classes guideline. But I find some classes where it's unclear why skos:altLabel is used instead: is that a mistake? Eg

```ttl
fibo-fnd-aap-ppl:NationalIdentificationNumber
        rdfs:label                   "national identification number" ;
        skos:altLabel                "national insurance number" ;
        fibo-fnd-utl-av:synonym      "national identity number" .

lcc-lr:LanguageIdentifier
        rdfs:label        "language identifier" ;
        skos:altLabel     "language symbol" ;

fibo-fnd-law-jur:StatuteLaw
        rdfs:label        "statute law"@en ;
        skos:altLabel     "statutory law" ;
```

**Comment by ElisaKendall** [comment]
LCC does not have the notion of a synonym in its annotations - that's a FIBO annotation, so I would not expect it to be on language identifier, but we deprecated altLabel in FIBO in favor of the more specific annotations.  I suspect these are there simply due to historic reasons and were not picked up as changes were made to the ontologies.

**Comment by VladimirAlexiev** [comment]
Agreed. So to concretize the tasks:
- remove skos:altLabel from fibo-fnd-aap-ppl:NationalIdentificationNumber, fibo-fnd-law-jur:StatuteLaw
- search for other altLabels on FIBO classes and properties
- Explain in the GUIDE why use `fibo-fnd-utl-av:synonym` instead of `skos:altLabel` (because there are other subprops of `skos:altLabel`)

**Comment by trypuz** [comment]
@ElisaKendall I'll be updating the ontology guide. If you agree with @VladimirAlexiev's suggestions, LMK what should be changed in the guide as far as  fibo-fnd-utl-av:synonym and skos:altLabel are concerned.

**Comment by VladimirAlexiev** [comment]
@trypuz Suggested clarifications:
1. External ontologies (eg `LCC`) usually use `skos:altLabel` to define synonyms of classes and properties.
2. However, FIBO ontologies use the `fibo-fnd-utl-av:synonym` sub-property for this purpose
3. FIBO has defined a number of other sub-properties of `skos:altLabel` that are used for different purposes:
  - `fibo-fnd-utl-av:abbreviation`: TODO
  - `fibo-fnd-utl-av:commonDesignation`: TODO
  - `fibo-fnd-utl-av:preferredDesignation`: TODO
  - `fibo-fnd-utl-av:symbol`: TODO
