### ISSUE TITLE
MetadataFIBO does not load all of the FIBO content

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/fibo#993]
The MetadataFIBO ontology is used by some tools, such as the FIBO Viewer, to support documentation that is published online.  While the metadata for some modules is scant or duplicative, it's better than nothing and should at least support our online documentation processes.  However,  testing confirms that only some of the ontologies are loaded when you load the primary MetadataFIBO ontology, not all, likely due to bugs in some of the lower level metadata files.  These bugs should be corrected ASAP so that, at a minimum, the metadata ontologies are complete and load properly together with the ontologies they describe.

**Comment by rivettp** [comment]
Can you provide the results of your testing?

**Comment by ElisaKendall** [comment]
The basic number of classes was 1/2 what I anticipated, and when I walked through it to review the metadata for each module, some were missing, for example, the CorporateEventsModule was not loaded.  I'm not sure which others, and don't know whether it is important for the metadata ontologies to load the ontologies they describe.  I've sent Robert a question on that.  If the metadata ontologies load the 'real' ontologies then the number of individuals should be greater than those in the basic ontologies, since they would include the named individuals in the metadata files.  I have a spreadsheet that documents the total number of individuals loaded by each of the "all" files, but some of them also load all of the North American and European country subdivisions, which AboutFIBOProd and AboutFIBODev do not load.  Having said this, if the metadata files load the actual ontologies, there should be a consistent relationship that is verifiable between the number of individuals in the ontologies, excluding the un-used country subdivisions and the number loaded by the metadata ontologies.  And, if the metadata ontologies load the others, there would be no need for an AboutFIBODev.rdf file, since that's what the metadata ontologies would load.

What in addition to the above would you want to know - do you care about the enumerated list of metadata files that were not loaded once I've done a thorough review, or just the fixes?

**Comment by ElisaKendall** [comment]
Issues include versionIRIs that do not align with either the OMG style IRis or anything published, imports issues (the MetadataCAE ontology imported the corporate actions and events ontology rather than the metadata ontology for the module), etc. so far.  The metadata for released ontologies appears to be ok, but the others have likely not been reviewed in quite awhile for correctness.

**Comment by rivettp** [comment]
It was never the intent for the MetadataX files to do the loading - we have the LoadX files for that, as you point out. Do you really see the need for both?

I've provided several comments on the PR on the assumption that there is a genuine problem (which I'm not at all convinced of, as per my previous sentence).
To address your comment about versionIRI, I believe the design replaces all versionIRIs in the publishing process anyway, so adding them manually in the source seems like a waste of time. While I don't like the current scheme, whatever we move to should be automated.

**Comment by trypuz** [comment]
LoadFIBODev and LoadFIBOProd (on our website) do not import metadata ontologies.

**Comment by ElisaKendall** [comment]
What I saw was quite confusing at first.  Some of the actual ontologies were being loaded by MetadataFIBO but only some of them.  As it happens, the CAE metadata file was loading the real CAE ontology not the metadata ontology as it should have done.  The correction in the pull request fixes this, and now MetadataFIBO only loads metadata ontologies as it should have done from that outset, and they are all loaded properly.  Further, the fix eliminates some weird blended version IRIs that were a combination of release-style (but not correct release-style) and date/nn OMG style IRIs. They are now normalized to OMG-styling.
