### ISSUE TITLE
Undesirable value for rdfs:seeAlso triples on all ontologies.

### ISSUE THREAD

**Issue by rivettp** [edmcouncil/fibo#998]
rdfs:seeAlso triples all have value of spec.edmcouncil.org/fibo/ while not illegal is bad practice IMO, since as W3C says w3.org/wiki/UsingSeeAlso "It is reasonable to expect many (probably even "most") rdfs:seeAlso properties to reference to RDF/XML documents. ". Given that we do have a proper RDF resource describing FIBO I strongly feel we should reference that i.e. the MetadataFIBO resource.

**Comment by mereolog** [comment]
Should we have a hygiene test for this issue?

**Comment by mereolog** [comment]
Closed to the lack of activity.
